pkg/apis/federation/zz_generated.api.register.go

Updates after running `apiserver-boot`.

Update generated code

---

pkg/apis/federation/v1alpha1/federatedconfigmap_types.go
pkg/apis/federation/zz_generated.api.register.go
pkg/openapi/openapi_generated.go

@marun @font 
Not sure whether or not I've to re-generate something...

minor fix in federated configmap resource

---

pkg/controller/sync/controller.go

This removes a lot of the anonymous function closures and indirection in the reconcile loop, which I think improves readability and maintenance.

Refactor reconcile loop

---

pkg/controller/sync/controller.go
pkg/controller/sync/placement/namespace.go
pkg/controller/sync/placement/plugin.go
pkg/controller/sync/placement/resource.go

This is in anticipation of computing namespace placement differently.
cc: @font

Refactor placement computation into plugin

---

cmd/controller-manager/main.go
pkg/controller/sync/controller.go
pkg/controller/sync/placement/plugin.go
pkg/controller/sync/placement/resource.go
pkg/controller/util/genericinformer.go
pkg/federatedtypes/adapter.go
pkg/federatedtypes/configmap.go
pkg/federatedtypes/deployment.go
pkg/federatedtypes/job.go
pkg/federatedtypes/namespace.go
pkg/federatedtypes/replicaset.go
pkg/federatedtypes/secret.go
pkg/federatedtypes/version.go
test/integration/framework/controller.go

This is foundational for computing placement for namespaces.
cc: @font

Use generic informers for placement

---

README.md
code-of-conduct.md

Adopt the Kubernetes code of conduct to prepare for donation to kubernetes-sigs github org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marun/federation-v2/54)

Adopt Kubernetes code of conduct

---

.travis.yml
scripts/download-test-binaries.sh
scripts/pre-commit.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marun/federation-v2/53)

Add travis config

---

cmd/kubefnord/kubefnord.go

This enables authenticating with various cloud providers e.g. GCP, Azure, etc.

Enable auth for cloud providers

---

README.md

cc @marun @onyiny-ang @sdminonne @pmorie Feel free to give this a try. It is still WIP but I wanted to get this out there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marun/federation-v2/36)

Document E2E tests

---

cmd/controller-manager/main.go
pkg/apis/federation/v1alpha1/federateddeploymentoverride_types.go
pkg/apis/federation/v1alpha1/federatedjoboverride_types.go
pkg/apis/federation/v1alpha1/federatedreplicasetoverride_types.go
pkg/apis/federation/v1alpha1/federatedsecretoverride_types.go
pkg/controller/sync/controller.go
pkg/controller/sync/placement/namespace.go
pkg/controller/util/federated_informer.go
pkg/controller/util/federated_updater.go
pkg/federatedtypes/configmap.go
pkg/federatedtypes/deployment.go
pkg/federatedtypes/job.go
pkg/federatedtypes/registry.go
pkg/federatedtypes/replicaset.go
pkg/federatedtypes/secret.go
test/e2e/crud.go
test/e2e/framework/framework.go
test/e2e/framework/managed.go
test/e2e/framework/unmanaged.go
test/integration/crud_test.go
test/integration/framework/controller.go

Migrate sync controller to use the dynamic client

---

test/common/crudtester.go

Ref: https://github.com/kubernetes-sigs/federation-v2/issues/78
/assign @marun

Fix a flake issue in integration test

---

OWNERS

Update owners file to add folks from Huawei

---

cmd/controller-manager/main.go
pkg/features/features.go

Ref: #101 
here is an first cut attempt to implement feature-gates to control which features(controllers as of now) should be enabled. Is this what is desired?
/cc @marun @pmorie @irfanurrehman

Add feature gates

---

OWNERS

Add pmorie to approvers

---

pkg/apis/core/v1alpha1/federatedcluster_types_test.go
test/integration/framework/framework_test.go

Namespace was missing from test files which caused image build to fail.

Add util.FederatedSystemNamespace where it is missing

---

docs/development.md

Updated integration link for development guide.

---

pkg/kubefnord/join.go

Fixed https://github.com/kubernetes-sigs/federation-v2/issues/145
/cc @marun @shashidharatd @onyiny-ang

Need to specify sa namespace when create clusterrolebindings.

---

hack/install-latest.yaml
images/federation-v2/Dockerfile
scripts/delete-federation.sh
scripts/deploy-federation-latest.sh
scripts/deploy-federation.sh
scripts/imagebuild.sh

Also includes #140 > merge first
-  updates `scripts/imagebuild.sh` for kubebuilder merge
-  updates `scripts/deploy-federation.sh`, `scripts/deploy-federation-latest.sh` and `hack/install-latest.sh` to point to the image built by master
-  fixes `scripts/delete-federation.sh` by pointing to `hack/install-latest.sh` which is not contingent on a new image being built
- updates `docs/userguide.md` to reflect changes
Just to create a record of it, I'm currently seeing this output with join command (no matter which image I use). The ERROR message doesn't seem to actually indicate an error.
```
ERROR: logging before flag.Parse: I0703 23:37:39.169435   14507 join.go:125] Defaulting cluster context to joining cluster name us-east
ERROR: logging before flag.Parse: I0703 23:37:39.169516   14507 …
```

Update image build to incorporate kubebuilder merge

---

pkg/kubefed2/join.go

/cc @marun @shashidharatd @onyiny-ang

Add more debug log in join.

---

scripts/imagebuild.sh

Update travis.yml to include support for tagging

---

scripts/imagebuild.sh

Slight change in regex for imagebuild to follow convention
/cc @pmorie @shashidharatd

Fix tagging format for image build

---

scripts/imagebuild.sh

Echo travis branch/tag ENV VARS

---

Makefile
cmd/controller-manager/main.go
pkg/kubefed2/version.go
pkg/version/base.go
pkg/version/version.go

Raising this pull to get feedback.
Some comments explaining, what I intend to do.
Alternative suggestions welcome.
@kubernetes-sigs/federation-wg

Implement versioning with git tag and sha info

---

pkg/kubefed2/kubefed2.go

Updated KubeFnord to KubeFed2.

---

test/integration/servicedns_test.go

Fixes #169 
/cc @onyiny-ang @marun

Introduce retry loop for federatedcluster status update

---

pkg/kubefed2/join.go
pkg/kubefed2/options/options.go

Fixed https://github.com/kubernetes-sigs/federation-v2/issues/165
/cc @font @marun

Rename `Host` to `HostClusterContext` for `join`.

---

cmd/controller-manager/main.go

Flush log immediately for controller manager.

---

docs/development.md

Correct the path for docker file.

---

pkg/kubefed2/join.go

Fix join to use passed-in federation namespace instead of a constant

---

pkg/kubefed2/kubefed2.go
pkg/kubefed2/unjoin.go

Fixed #127
/cc @marun @onyiny-ang

Implemented unjoin.

---

CONTRIBUTING.md

Adding Contribution guidelines for kubernetes federation-v2.
fixes #183

Adding Contribution guidelines 

---

scripts/delete-federation.sh

Use unjoin when remove cluster from federation.

---

docs/userguide.md

Updated userguide to highlight the usage of automatic deploy and delete.

---

docs/userguide.md
scripts/download-binaries.sh

Update kubebuilder binary version to 1.0.0

---

pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
pkg/apis/multiclusterdns/v1alpha1/multiclusterservicednsrecord_types.go
pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
pkg/controller/servicednsendpoint/servicednsendpoint_controller.go
pkg/controller/servicednsendpoint/servicednsendpoint_controller_test.go
test/e2e/servicedns.go

Addresses https://github.com/kubernetes-sigs/federation-v2/issues/201
/cc @font @kubernetes-sigs/federation-wg

Make DNS record TTL configurable by user

---

pkg/kubefed2/join.go
pkg/kubefed2/options/options.go
pkg/kubefed2/unjoin.go

Enable kubefed2 config of federation and cluster namespaces

---

cmd/controller-manager/main.go
pkg/controller/federatedcluster/clusterclient.go
pkg/controller/federatedcluster/controller.go
pkg/controller/federatedtypeconfig/controller.go
pkg/controller/schedulingpreference/controller.go
pkg/controller/servicedns/controller.go
pkg/controller/sync/controller.go
pkg/controller/util/cluster_util.go
pkg/controller/util/federated_informer.go
pkg/schedulingtypes/interface.go
pkg/schedulingtypes/plugin.go
pkg/schedulingtypes/replicascheduler.go
test/e2e/framework/managed.go
test/e2e/framework/test_context.go
test/e2e/framework/unmanaged.go
test/integration/crud_test.go
test/integration/framework/controller.go
test/integration/framework/federation.go
test/integration/integration_test.go
test/integration/replicaschedulingpreference_test.go
test/integration/servicedns_test.go

Allow the cluster registry namespace to vary in testing

---

pkg/apis/core/v1alpha1/federatednamespaceplacement_types.go
pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatednamespaceplacement.go
pkg/client/clientset/versioned/typed/core/v1alpha1/federatednamespaceplacement.go
pkg/client/informers/externalversions/core/v1alpha1/federatednamespaceplacement.go
pkg/client/informers/externalversions/core/v1alpha1/interface.go
pkg/client/listers/core/v1alpha1/expansion_generated.go
pkg/client/listers/core/v1alpha1/federatednamespaceplacement.go

Update FederatedNamespacePlacement to be namespace-scoped

---

pkg/kubefed2/join.go
pkg/kubefed2/options/options.go
pkg/kubefed2/unjoin.go
pkg/kubefed2/util/util.go

Enable kubefed to join a cluster for only the federation namespace

---

cmd/controller-manager/main.go
pkg/controller/federatedtypeconfig/controller.go
pkg/controller/schedulingpreference/controller.go
pkg/controller/servicedns/controller.go
pkg/controller/sync/controller.go
pkg/controller/util/federated_informer.go
pkg/schedulingtypes/interface.go
pkg/schedulingtypes/plugin.go
pkg/schedulingtypes/replicascheduler.go
test/e2e/framework/managed.go
test/e2e/framework/test_context.go
test/e2e/framework/unmanaged.go
test/integration/crud_test.go
test/integration/framework/controller.go
test/integration/integration_test.go
test/integration/replicaschedulingpreference_test.go
test/integration/servicedns_test.go

Allow the target namespace to vary in testing

---

pkg/controller/util/federated_informer.go

Reduces confusing error messages from FederatedInformer

Reduce federated informer error messages

---

cmd/controller-manager/main.go

Also converted to use glog instead of log.

Log federation-v2 version in controller-manager

---

pkg/apis/core/v1alpha1/federatedcluster_types.go

Add godoc for FederatedCluster

---

Gopkg.toml

Added back github.com/kubernetes/repo-infra to Gopkg.toml

---

pkg/controller/federatedcluster/clusterclient.go
pkg/controller/federatedcluster/controller.go
pkg/controller/util/cluster_util.go

Add a bit of godoc for FederatedCluster controller.

Add godoc for FederatedCluster controller

---

docs/userguide.md
example/sample1/federateddeployment-template.yaml
example/sample1/federatedjob-override.yaml
example/sample1/federatedjob-placement.yaml
example/sample1/federatedjob-template.yaml

This fixed part of https://github.com/kubernetes-sigs/federation-v2/issues/262
/cc @irfanurrehman @pmorie @marun

Added example for federatedJob.

---

docs/development.md
docs/userguide.md

Update docs on using master canary or latest stable version image

---

docs/userguide.md

Add doc for deployment of namespaced federation

---

pkg/controller/sync/controller.go

This fixes a known issue which was causing build to fail sometimes due to concurrent read-write to maps.
/cc @marun @font

Lock pendingVersionUpdates

---

pkg/apis/core/v1alpha1/federatedtypeconfig_types.go

Adds godoc for `FederatedTypeConfig`

Add godoc for FederatedTypeConfig

---

example/scheduling/federateddeployment-rsp.yaml

Fixed part of https://github.com/kubernetes-sigs/federation-v2/issues/262
/cc @irfanurrehman @marun @font

Added ReplicaSchedulingPreference example.

---

README.md

Add quay badge to README

---

charts/federation-v2/Chart.yaml
charts/federation-v2/LICENSE
charts/federation-v2/README.md
charts/federation-v2/charts/clusterregistry/Chart.yaml
charts/federation-v2/charts/clusterregistry/templates/_helpers.tpl
charts/federation-v2/charts/clusterregistry/templates/crds.yaml
charts/federation-v2/charts/federatedtypes/Chart.yaml
charts/federation-v2/charts/federatedtypes/templates/_helpers.tpl
charts/federation-v2/charts/federatedtypes/templates/configmap.yaml
charts/federation-v2/charts/federatedtypes/templates/deployment.yaml
charts/federation-v2/charts/federatedtypes/templates/ingress.yaml
charts/federation-v2/charts/federatedtypes/templates/job.yaml
charts/federation-v2/charts/federatedtypes/templates/namespace.yaml
charts/federation-v2/charts/federatedtypes/templates/replicaset.yaml
charts/federation-v2/charts/federatedtypes/templates/secret.yaml
charts/federation-v2/charts/federatedtypes/templates/service.yaml
charts/federation-v2/charts/federatedtypes/templates/serviceaccount.yaml
charts/federation-v2/requirements.yaml
charts/federation-v2/templates/_helpers.tpl
charts/federation-v2/templates/clusterrole.yaml
charts/federation-v2/templates/clusterrolebindings.yaml
charts/federation-v2/templates/crds.yaml
charts/federation-v2/templates/service.yaml
charts/federation-v2/templates/statefulset.yaml
charts/federation-v2/values.yaml

/cc @pmorie @shashidharatd @marun @font @irfanurrehman

Helm chart for federation v2.

---

scripts/generate-install-crds-yaml.sh

Added "--name federation" for crd generation script.

---

OWNERS

Adding myself as reviewer.

---

charts/federation-v2/README.md
charts/federation-v2/templates/role.yaml
charts/federation-v2/templates/rolebindings.yaml
charts/federation-v2/templates/statefulset.yaml
charts/federation-v2/values.yaml

Added more parameters for federation chart.

---

pkg/controller/util/overrides.go
pkg/controller/util/worker.go

- [Fix comment for reconcile worker](https://github.com/kubernetes-sigs/federation-v2/pull/296#discussion_r222028975)
- [Rename poorly named method](
https://github.com/kubernetes-sigs/federation-v2/pull/266#discussion_r220426080)
- [Return early from unmarshallOverrides](
https://github.com/kubernetes-sigs/federation-v2/pull/266#discussion_r220341343)

Misc fixes for font comments on previous PRs

---

scripts/delete-federation.sh
scripts/deploy-federation.sh
scripts/generate-install-yaml.sh
scripts/generate-namespaced-install-yaml.sh

This PR enables end user can select the namespace that want to use
when deploying a cluster scoped federation controller.
/cc @marun

Fine-grained deploy for cluster scoped federation controller.

---

Makefile
scripts/pre-commit.sh

Use Makefile to build binaries with version info

---

pkg/apis/core/v1alpha1/propagatedversion_types.go

Adds API godoc for PropagatedVersion explaining how push propagation uses it.

Add godoc for PropagatedVersion

---

docs/userguide.md

Updated user guide for namespaced federation.

---

docs/federating_crds.md
docs/userguide.md

Created a document to demonstrate an example to federate a CRD in the target cluster.

Example to federate a CRD in the target cluster

---

scripts/pre-commit.sh

Prompted by a [comment](https://github.com/kubernetes-sigs/federation-v2/pull/331) on #331.

Add ci check for 'kubebuilder generate' making no changes

---

docs/environments/gke.md
docs/environments/minikube.md
docs/userguide.md

Fixes Issue https://github.com/kubernetes-sigs/federation-v2/issues/310

Adds GKE Deployment Documentation

---

example/sample1/federatedconfigmap-override.yaml
example/sample1/federatedconfigmap-placement.yaml
example/sample1/federatedconfigmap-template.yaml
example/sample1/federateddeployment-override.yaml
example/sample1/federateddeployment-placement.yaml
example/sample1/federateddeployment-template.yaml
example/sample1/federatedjob-placement.yaml
example/sample1/federatednamespace-placement.yaml
example/sample1/federatedsecret-override.yaml
example/sample1/federatedsecret-placement.yaml
example/sample1/federatedsecret-template.yaml
example/sample1/federatedserviceaccount-placement.yaml
example/sample1/federatedserviceaccount-template.yaml

Removed the List from all exampes.

---

docs/userguide.md

/cc @marun @pmorie @shashidharatd

Updated user guide by adding steps for helm chart install.

---

docs/federating_crds.md
example/crd/bar_crd.yaml
example/crd/federatedbar_crd.yaml

Fix validation verification and remove `--validate=false` from `kubectl` commands

Fix validation

---

pkg/controller/util/planner/planner_test.go

Signed-off-by: mooncake <xcoder@tenxcloud.com>
Fix typos: fuly -> fully

Fix typos: fuly -> fully

---

pkg/controller/schedulingpreference/controller.go

Fix typos: syncronises -> synchronises

Fix typos: syncronises -> synchronises

---

docs/userguide.md

Fixed https://github.com/kubernetes-sigs/federation-v2/issues/350
/cc @danehans @marun @font

Added a troubleshooting section for user guide.

---

hack/go-tools/verify-gofmt.sh
hack/update-gofmt.sh
pkg/controller/sync/controller.go
scripts/pre-commit.sh
test/e2e/crud.go
test/integration/framework/federation.go
test/integration/servicedns_test.go

Adding Go-fmt tools and fixing go-fmt errors

---

charts/federation-v2/templates/configmap.yaml
charts/federation-v2/templates/deployment.yaml
charts/federation-v2/templates/job.yaml
charts/federation-v2/templates/replicaset.yaml
charts/federation-v2/templates/secret.yaml

Follow-up of #357
/cc @marun @irfanurrehman @shashidharatd

update yaml in chart to reflect multiple override format

---

scripts/pre-commit.sh

Disable gofmt check until it can be made reliable

---

docs/environments/minikube.md

Released versions of minikube now support profiles properly.

Update minikube instructions to reflect released version state

---

docs/userguide.md

Add missing weight to user guide RSP example

---

pkg/controller/schedulingpreference/controller.go

Fix typos: triggerred -> triggered

Fix typos: triggerred -> triggered

---

scripts/pre-commit.sh

ref: https://github.com/kubernetes-sigs/federation-v2/pull/390#issuecomment-436140394 
and 
#393

Re-enabling the gofmt CI check

---

charts/federation-v2/charts/controllermanager/templates/crds.yaml
charts/federation-v2/templates/service.yaml

/cc @marun @shashidharatd @pmorie
I will update document as well for how to update the chart with https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/generate-install-crds-yaml.sh

Updated helm chart based on latest code.

---

pkg/schedulingtypes/replicascheduler.go

Update the comment of the function

Update the comment of the function

---

docs/userguide.md

/cc @irfanurrehman @shashidharatd

Remove manual install for federation.

---

pkg/kubefed2/unjoin.go

Fix #188 
unjoin should always to be executed to be finished if some of resources are failed in
deletion
@gyliu513

always unjoin if any resource is failed in deletion

---

pkg/controller/sync/version/adapter.go
pkg/controller/util/handlers.go

Remove excess code

---

docs/userguide.md

Added some detail to let end user check `Status.Conditions` for
cluster info.

Added more detail for how to check if a joined cluster is ready.

---

pkg/controller/sync/controller.go

There previously existed logic to avoid performing updates to namespaces in the host cluster.  This PR extends that logic to cover deletions and simplifies the comments for clarity.
Fixes #396

Cleanup operation logic for namespaces in the host cluster

---

docs/concepts.md
docs/userguide.md

/cc @marun @pmorie @irfanurrehman @shashidharatd @danehans

Added Fed V2 concepts document.

---

docs/environments/kind.md

Minor fix for kind document.

---

example/sample1/federatedconfigmap-override.yaml
example/sample1/federatedconfigmap-placement.yaml
example/sample1/federatedconfigmap-template.yaml
example/sample1/federateddeployment-override.yaml
example/sample1/federateddeployment-placement.yaml
example/sample1/federateddeployment-template.yaml
example/sample1/federatedingress-placement.yaml
example/sample1/federatedingress-template.yaml
example/sample1/federatedjob-override.yaml
example/sample1/federatedjob-placement.yaml
example/sample1/federatedjob-template.yaml
example/sample1/federatednamespace-placement.yaml
example/sample1/federatedsecret-override.yaml
example/sample1/federatedsecret-placement.yaml
example/sample1/federatedsecret-template.yaml
example/sample1/federatedservice-placement.yaml
example/sample1/federatedservice-template.yaml
example/sample1/federatedserviceaccount-placement.yaml
example/sample1/federatedserviceaccount-template.yaml

Changed apiVerison from core.federation.k8s.io/v1alpha1 to primitives.federation.k8s.io/v1alpha1

---

cmd/controller-manager/app/controller-manager.go

fix flag include problem

---

docs/userguide.md

Use `yaml` for yaml files in user guide.

---

docs/development.md

comment the suggested docker version in the user guide

---

.github/PULL_REQUEST_TEMP

Added a PR template.

---

docs/userguide.md
pkg/kubefed2/federate/enable.go

Fixes prompted by @gyliu513 on #503.

Fixes for PR503 

---

docs/userguide.md

Fixed https://github.com/kubernetes-sigs/federation-v2/issues/490
/cc @marun

Added document for clusterSelector.

---

Makefile
docs/development.md

1. fix e2e example case to make it work successfuly
2. upgrade golang in Makefile to make it consistent with .travis

fix e2e example in development.md and go version

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/failing-test.md
.github/ISSUE_TEMPLATE/support.md

Copy from Kubernetes issue template.

Added issue template.

---

docs/userguide.md
pkg/kubefed2/federate/disable.go
pkg/kubefed2/federate/enable.go

As a follow up for #534 
cc @marun @gyliu513 @xunpan

Update docs and comments for 'federate enable/disable'

---

pkg/kubefed2/unjoin.go

Previously unjoin was comparing the context names of the host and unjoining cluster, and removing the federation namespace in the unjoining cluster if the names didn't match.   If the host context name was not specified, though, a value of empty string (`""`) would be used and the federation namespace would always be removed even for the host cluster.  This PR switches to comparing the identities of the federation namespace in the host and unjoining clusters and only removing the namespace if the 2 don't match.
I've cleaned up the logging in this function, which now deviates from the rest of join/unjoin in its formatting.  I'll leave it up to the reviewers whether this PR should be updated for consistency or the rest of the code should be updated in a subsequent PR.
Fixes #593

Fix unjoin to use namespace identity instead of context name as criteria for removal

---

.travis.yml
hack/verify-docfiles.sh

Skip Travis build for doc-only changes

---

docs/ingress-service-dns-with-coredns.md
docs/servicedns-with-externaldns.md

after unifying template, override and placement into one, these document is not updated accordingly. Just fix them.

use new federatedservice.yaml file in service dns document

---

pkg/kubefed2/join.go

Introduces a flag to the JoinCluster function that specifies whether to run in idempotent mode. If true, creates that fail because the resource already exists will not fail the entire operation.

Allow join command to run in idempotent mode

---

pkg/kubefed2/federate/disable.go
pkg/kubefed2/federate/util.go

- `kubefed2 disable` is supported to use kind and short name in command line 
- if multiple resource names are matched by kind/short name, reject the operation and print error message to let end user specify a group-qualified name.
Fixes #608

Short name support in kubefed2 disable and reject case if multiple resource name matched

---

README.md

Adds a feature matrix to the README per Jan 23 working group meeting

Add feature matrix to README

---

pkg/controller/federatedtypeconfig/controller.go

This message is not necessary. It makes log message not readable because lots of them printed quickly.
Refer to https://github.com/kubernetes-sigs/federation-v2/pull/617#discussion_r261435218 for information

make log level lower to consist with reconcile message 

---

.travis.yml
Makefile
cmd/kubefed2/kubefed2.go
hack/boilerplate.go.txt
pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
pkg/apis/multiclusterdns/doc.go
pkg/apis/multiclusterdns/v1alpha1/doc.go
pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
pkg/apis/scheduling/v1alpha1/zz_generated.kubebuilder.go
pkg/controller/doc.go
pkg/controller/ingressdns/controller.go
pkg/controller/schedulingpreference/controller.go
pkg/controller/servicedns/controller.go
pkg/controller/sharedinformers/doc.go
pkg/doc.go
pkg/inject/zz_generated.kubebuilder.go
pkg/kubefed2/unjoin.go
test/e2e/scheduling.go

There was an issue in calling `verify-boilerplate.sh` from CI, due to which some issues related to boilerplate crept in. This PR fixes those issues.

Fix Boilerplate issues

---

pkg/controller/schedulingmanager/controller.go
pkg/controller/util/safe_map.go
pkg/schedulingtypes/replicascheduler.go
scripts/pre-commit.sh

I have chosen to use fine grained locking, which seems more suitable given the small number of values stored in the maps/sets in question.
cc @marun @shashidharatd

Fix races in replica scheduling code

---

pkg/controller/util/handlers.go
pkg/controller/util/handlers_test.go

The following handlers need the same change but it seems that
they are currently unused:
NewTriggerOnMetaAndSpecChanges
NewTriggerOnMetaAndFieldChanges

Handle events with DeletedFinalStateUnknown

---

pkg/kubefed2/enable/enable.go

Keep the default command behavior same as before for cluster federation deployment.
For namespaced deployment,
when enable a federated resource, if the federaed* CRD exists, reuse it. If the CRD does not exist, create it. "--error-on-existing=false" need to be used.
when disable a federated resource,  CRD should not be deleted because other deployment may use it. "--delete-crd=false" need to be used.

support federated resource CRD sharing for namespaced installation

---

docs/userguide.md

User guide doesn't cover `unjoin`
fixes #638

User guide doesn't cover `unjoin`

---

Makefile
scripts/download-binaries.sh
scripts/pre-commit.sh

Some OSX support

---

pkg/kubefed2/federate/federate.go
test/common/crudtester.go
test/common/resource_helper.go
test/common/testobjects.go
test/e2e/crud.go
test/e2e/federate.go

Refactored wrt to the follow up comment from older work [here] (https://github.com/kubernetes-sigs/federation-v2/pull/607#discussion_r260612539).
cc @marun

Refactor federate resource to simplify crud tests

---

Makefile

follow up task to https://github.com/kubernetes-sigs/federation-v2/pull/361 
part of https://github.com/kubernetes-sigs/federation-v2/issues/364

Integrating fmt update in makefile

---

docs/userguide.md

This PR fixes invalid table format in userguide.

Fix invalid table format in userguide

---

pkg/kubefed2/federate/federate.go

Accept group qualified type name for type in federate resource

---

cmd/controller-manager/app/controller-manager.go
pkg/controller/schedulingmanager/controller.go
pkg/controller/schedulingpreference/controller.go
pkg/controller/util/safe_map.go
pkg/schedulingtypes/interface.go
pkg/schedulingtypes/replicascheduler.go
test/e2e/framework/managed/controller.go
test/e2e/scheduling.go

Fixes https://github.com/kubernetes-sigs/federation-v2/issues/676

Refactor scheduling manager to correct goroutine usage

---

pkg/controller/status/controller.go

Issue:https://github.com/kubernetes-sigs/federation-v2/issues/677

fix status controller not reconcile when federation has no readyCluster

---

scripts/pre-commit.sh

- Move helm chart check before tests are run
- Ensure echo text matches the actions performed

Cleanup ci script

---

docs/userguide.md

Helm is the only supportable deployment option, so documenting a script-based way of deploying is just asking for user confusion.
Fixes #565

Remove mention of script-based install from the user guide

---

pkg/kubefed2/enable/enable.go

kubefed2 enable now succeeds if federation of the type is already enabled. If the federated type is already enabled, it will update the FederatedTypeConfig to stay consistent with #628 for CRDs.
Fixes #720

kubefed2 enable succeeds if federation of the type already enabled

---

pkg/kubefed2/disable.go
pkg/kubefed2/enable/enable.go
pkg/kubefed2/federate/federate.go
pkg/kubefed2/join.go
pkg/kubefed2/options/options.go
pkg/kubefed2/unjoin.go

Cleanup and rework some of the kubefed2 options to improve usability and maintainability.
Fixes #738

Cleanup kubefed2 subcommand options

---

pkg/kubefed2/federate/federate.go
test/e2e/federate.go

Implement optional --enable-type in federate resource

---

charts/federation-v2/charts/controllermanager/templates/clusterrolebindings.yaml
charts/federation-v2/charts/controllermanager/templates/deployment.yaml
charts/federation-v2/charts/controllermanager/templates/rolebindings.yaml
charts/federation-v2/charts/controllermanager/templates/serviceaccout.yaml

user federation-controller sa instead of the default one

---

pkg/controller/sync/resource.go
pkg/controller/sync/updater.go
pkg/controller/util/managedlabel.go
pkg/controller/util/resourceinformer.go
test/common/crudtester.go

6th in a series targeting #612

Add helpers to [ check for | add | remove ] the managed label

---

charts/federation-v2/README.md
docs/releasing.md

We have a released chart but no instructions on how to use it.   This needs to merge ASAP.
Supersedes #751 
Fixes #701

Update instructions for chart release and installation.

---

.golangci.yml
.travis.yml
cmd/hyperfed/main.go
pkg/controller/dnsendpoint/controller.go
pkg/controller/schedulingmanager/controller.go
pkg/controller/schedulingpreference/controller.go
pkg/controller/servicedns/controller.go
pkg/controller/sync/dispatch/retain_test.go
pkg/controller/sync/placement_test.go
pkg/controller/sync/resource.go
pkg/controller/util/cluster_util.go
pkg/controller/util/federated_updater.go
pkg/controller/util/meta.go
pkg/controller/util/planner/planner.go
pkg/controller/util/planner/planner_test.go
pkg/controller/util/podanalyzer/pod_helper_test.go
pkg/features/features.go
pkg/kubefed2/disable.go
pkg/kubefed2/enable/enable.go
pkg/kubefed2/join.go
pkg/kubefed2/kubefed2.go
pkg/kubefed2/unjoin.go
pkg/schedulingtypes/plugin.go
pkg/schedulingtypes/replicascheduler.go
test/common/crudtester.go
test/e2e/crud.go
test/e2e/framework/framework.go
test/e2e/framework/unmanaged.go
test/e2e/ingressdns.go
test/e2e/servicedns.go

add golangci lint to travis

---

charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
charts/federation-v2/charts/controllermanager/templates/role.yaml

update RBAC with more detailed permission

---

charts/federation-v2/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1alpha1/federatedcluster_types.go

Add GoDoc to the `Name` field and mark it required.

LocalClusterReference updates

---

docs/userguide.md

Document how to determine that a target type is present in all federated clusters

---

cmd/controller-manager/app/controller-manager.go

Fixes #816 
See the issue for details.

Set default values for FederationConfig

---

pkg/controller/util/federated_informer.go

Increase log level of cluster status ok logs

---

pkg/kubefedctl/enable/util.go
pkg/kubefedctl/federate/federate.go
pkg/kubefedctl/federate/util.go
pkg/kubefedctl/util/yaml_writer.go
test/e2e/federate.go

Implement federate namespaces with content

---

CHANGELOG.md
charts/index.yaml

- Roll over the changelog
- Updating chart repo index

Update repo for v0.0.10 release

---

pkg/kubefedctl/enable/enable.go

Fixes #743 
if FTC exists, ensure that the group and version of the crd that will be generated match what exists (so it can update instead of creating a new one)
If group and version don't match - error.

if FTC is not same version/group, reject request

---

test/e2e/servicedns.go

Fixes: https://github.com/kubernetes-sigs/federation-v2/issues/839
/cc @marun

Retry updating federated cluster status in servicedns e2e test

---

docs/userguide.md

enable federation of types with federation group

---

pkg/kubefedctl/federate/federate.go
pkg/kubefedctl/federate/util.go
test/e2e/federate.go

- Provides an option to the user to skip API Resources while federating ns with contents.

Option to user to skip API Resources while federating ns with content

---

pkg/controller/sync/dispatch/checkunmanaged.go

#791 was merged after #851 was created so this last dangling reference was missed.

Fix dangling glog to klog

---

CHANGELOG.md
charts/federation-v2/README.md
config/federationconfig.yaml
docs/development.md
docs/ingress-service-dns-with-coredns.md
docs/servicedns-with-externaldns.md
docs/userguide.md
example/config/federationconfig.yaml
pkg/controller/util/cluster_util.go
scripts/delete-federation.sh
scripts/deploy-federation.sh
scripts/fix-ca-for-k3s.sh
scripts/pre-commit.sh
scripts/sync-up-helm-chart.sh

Rename the default system namespace to kube-federation-system

---

test/e2e/servicedns.go

Fixes: https://github.com/kubernetes-sigs/federation-v2/issues/839#issuecomment-492078999
/cc @marun @irfanurrehman

Fix retry logic while updating cluster status in e2e test

---

.travis.yml

Adds notes about how travis and quay settings are configured to push images to the quay repo.

Add note about configuration of travis and use of quay robot account

---

charts/kubefed/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1alpha1/federatedservicestatus_types.go

Align FederatedServiceStatus API with K8s API conventions

---

charts/kubefed/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1alpha1/propagatedversion_types.go
pkg/apis/core/v1alpha1/zz_generated.deepcopy.go

Align PropagatedVersion API with K8s API conventions

---

charts/kubefed/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1alpha1/clusterpropagatedversion_types.go
pkg/apis/core/v1alpha1/zz_generated.deepcopy.go

Align ClusterPropagatedVersion API with K8s API conventions

---

docs/userguide.md

Doc immutable limitation

---

docs/development.md
docs/installation.md
docs/userguide.md

Made the following changes
- split installation instructions out from user guide
- general review and editing of userguide.md, development.md and installation.md
- removed list of required binaries as this is superseded by Helm deployment
- updated links to installation instructions

Documentation changes for issue #728

---

docs/development.md
docs/installation.md
docs/userguide.md

I've replaced some initial instances, but this probably needs additional review from @shashidharatd - I'm not sure about federation in the names of scripts or in some of the contexts it has been used?

Changes to naming from Federation to Kubefed

---

README.md

Fixes a couple missed renames in the README

Missed federation -> kubefed renames

---

scripts/fix-ca-for-k3s.sh

- Add a missing backslash
- Specify patch type (otherwise the server complains)
- Update comments

Fix fix-ca-for-k3s.sh script

---

example/sample1/configmap.yaml
example/sample1/deployment.yaml
example/sample1/service.yaml
scripts/deploy-federated-nginx.sh
scripts/pre-commit.sh

Fixes #104 
Currently, service IP should be get from `minikube` command line. So, it works for `minikube` case and can be modified to work for other cases.

script for e2e use case of a simple nginx application

---

example/config/kubefedconfig.yaml

Found during testing my development work. A simple fix

update example of kubefedconfig.yaml use correct feature gates

---

charts/kubefed/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1beta1/kubefedcluster_types.go

Align KubefedCluster API with K8s API conventions

---

docs/userguide.md

Minor updates to naming in userguide, fixes for headings and formatting

---

docs/userguide.md

Fixing broken link

---

docs/releasing.md

Add release image verification steps

---

docs/development.md
docs/environments/gke.md
docs/installation.md
docs/servicedns-with-externaldns.md
docs/userguide.md

Partial fix for #936 
Fixed #891

Cleanup docs to reflect kubefed rename

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/failing-test.md
.github/ISSUE_TEMPLATE/support.md
.gitignore
charts/kubefed/charts/controllermanager/templates/crds.yaml
charts/kubefed/charts/controllermanager/templates/roles.yaml
charts/kubefed/values.yaml
docs/userguide.md
pkg/apis/core/v1alpha1/propagatedversion_types.go
pkg/apis/core/v1beta1/kubefedcluster_types.go
pkg/apis/core/v1beta1/kubefedconfig_types.go
pkg/apis/multiclusterdns/v1alpha1/domain_types.go
pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go

Cleanup misc to reflect kubefed rename

---

cmd/controller-manager/app/controller-manager.go
cmd/controller-manager/app/options/options.go
cmd/hyperfed/main.go
pkg/apis/core/typeconfig/util.go
pkg/apis/core/v1beta1/federatedtypeconfig_types.go
pkg/controller/federatedtypeconfig/controller.go
pkg/controller/ingressdns/controller.go
pkg/controller/schedulingpreference/controller.go
pkg/controller/servicedns/controller.go
pkg/controller/status/controller.go
pkg/controller/sync/controller.go
pkg/controller/sync/placement.go
pkg/controller/sync/resource.go
pkg/controller/util/controllerconfig.go
pkg/controller/util/federated_informer.go
pkg/controller/util/managedlabel.go
pkg/controller/util/resourceinformer.go
pkg/controller/util/worker.go
pkg/features/features.go
pkg/kubefedctl/enable/enable.go
pkg/kubefedctl/join.go
pkg/kubefedctl/options/options.go
pkg/kubefedctl/unjoin.go
pkg/schedulingtypes/interface.go
pkg/schedulingtypes/plugin.go
pkg/schedulingtypes/replicascheduler.go
test/common/crudtester.go
test/common/dns.go
test/e2e/framework/controller.go

Cleanup code to reflect kubefed rename

---

charts/kubefed/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1beta1/kubefedconfig_types.go

Response to https://github.com/kubernetes-sigs/kubefed/pull/937#discussion_r288352550

Fix crd doc formatting

---

charts/kubefed/charts/controllermanager/templates/deployments.yaml
images/kubefed/Dockerfile

adding non-root user to kubefed controller dockerfile #929

adding non-root user to dockerfile

---

test/common/crudtester.go
test/e2e/crd.go
test/e2e/crud.go
test/e2e/e2e.go
test/e2e/federate.go
test/e2e/framework/controller.go
test/e2e/framework/framework.go
test/e2e/framework/test_context.go
test/e2e/framework/unmanaged.go
test/e2e/ingressdns.go
test/e2e/leaderelection.go
test/e2e/placement.go
test/e2e/scheduling.go
test/e2e/servicedns.go
test/e2e/version.go

Cleanup tests to reflect kubefed rename

---

CHANGELOG.md
charts/kubefed/charts/controllermanager/templates/webhook.yaml
pkg/apis/core/typeconfig/util.go
pkg/apis/core/v1beta1/validation/validation.go
pkg/apis/core/v1beta1/validation/validation_test.go
pkg/controller/federatedtypeconfig/controller.go
pkg/controller/schedulingmanager/controller.go
pkg/controller/webhook/federatedtypeconfig/webhook.go
pkg/controller/webhook/federatedtypeconfig_webhook.go
pkg/controller/webhook/util.go
pkg/kubefedctl/enable/enable.go
pkg/kubefedctl/enable/util.go
pkg/webhook/webhook.go

Validation for FederatedTypeConfig API

---

Makefile
docs/development.md
docs/userguide.md
scripts/check-directive-fixtures.sh
scripts/delete-kubefed.sh
scripts/deploy-federated-nginx.sh
scripts/deploy-kubefed-latest.sh
scripts/deploy-kubefed.sh
scripts/download-binaries.sh
scripts/download-e2e-binaries.sh
scripts/pre-commit.sh
scripts/sync-up-helm-chart.sh

Cleanup scripts to reflect kubefed rename

---

charts/kubefed/README.md
charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
cmd/controller-manager/app/controller-manager.go
cmd/controller-manager/app/leaderelection/leaderelection.go
cmd/kubefedctl/main.go

More misc cleanup to reflect kubefed rename

---

scripts/deploy-federated-nginx.sh

fix walkthrough failed in CI

---

hack/verify-klog.sh
scripts/pre-commit.sh

Gate Check for Klog package

---

docs/ingressdns-with-externaldns.md

Fixes: https://github.com/kubernetes-sigs/kubefed/issues/963

Update IngressDNS user guide with a clarification

---

docs/cluster-registration.md
docs/releasing.md
docs/userguide.md

Moved join/unjoin operators into a new doc section and updated links in userguide.md.
Relates to #955 
Will add any new content in an additional PR.

Separated Cluster Registration into a new .md file

---

docs/cluster-registration.md

@marun this includes the changes discussed in our previous comments

Fixed minor comments for cluster registration doc

---

pkg/apis/core/v1beta1/validation/validation.go
pkg/apis/core/v1beta1/validation/validation_test.go

Assuming CI passes, please merge this ASAP.  Master is broken without it.

Fix lint errors introduced by #966 and #941 merging without rebase

---

CHANGELOG.md
charts/kubefed/README.md
charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
charts/kubefed/charts/controllermanager/templates/clusterrolebindings.yaml
charts/kubefed/charts/controllermanager/templates/rolebindings.yaml
charts/kubefed/charts/controllermanager/templates/roles.yaml
charts/kubefed/charts/controllermanager/templates/webhook.yaml
scripts/deploy-kubefed.sh

Add admission webhook support for namespace-scoped deployments

---

hack/go-tools/verify-gofmt.sh
hack/update-gofmt.sh
hack/verify-errpkg.sh

Clean up in the scripts after changes made in https://github.com/kubernetes-sigs/kubefed/pull/716

Minor Cleanup in the scripts

---

pkg/apis/core/v1beta1/validation/validation_test.go

This PR addresses the following comments from @marun made in previous PRs #914 and #941:
- https://github.com/kubernetes-sigs/kubefed/pull/914#discussion_r288971301
- https://github.com/kubernetes-sigs/kubefed/pull/914#discussion_r288979557
- https://github.com/kubernetes-sigs/kubefed/pull/941#pullrequestreview-247157071

Refactor and cleanup validation unit tests

---

README.md

The dynamic one will reflect the latest released version.

Update static release badge to a dynamic one

---

charts/kubefed/templates/crds.yaml
example/sample1/federatedconfigmap.yaml
example/sample1/federateddeployment.yaml
example/sample1/federatedjob.yaml
example/sample1/federatedsecret.yaml
pkg/controller/sync/resource.go
pkg/controller/util/overrides.go
pkg/kubefedctl/enable/validation.go
pkg/schedulingtypes/plugin.go
scripts/deploy-federated-nginx.sh
test/common/crudtester.go
test/common/fixtures/configmaps.yaml
test/common/fixtures/deployments.apps.yaml
test/common/fixtures/jobs.batch.yaml
test/common/fixtures/replicasets.apps.yaml
test/common/fixtures/secrets.yaml
test/e2e/crd.go

Please refer to the design doc [here](https://docs.google.com/document/d/1nUC4H7SsxhZPMO2aKap5GG6ZJoqdxbxaUvzlSt_dfuc/edit#)
Ref issue: https://github.com/kubernetes-sigs/kubefed/issues/520
todos:
/cc @marun

Replace override paths with JSON pointer style paths

---

pkg/controller/federatedtypeconfig/controller.go

Previously sync controllers for any type required namespaces are enabled for federation. This change ensures that sync controllers for cluster-scoped types can start if namespaces are not enabled.

Ensure cluster scoped sync controller starts without namespace ftc

---

pkg/controller/webhook/federatedtypeconfig/webhook.go
test/e2e/framework/framework.go
test/e2e/framework/unmanaged.go
test/e2e/validation.go

This is a partial fix for #944.

Add FederatedTypeConfig e2e validation webhook test

---

pkg/controller/federatedtypeconfig/controller.go

RE: https://github.com/kubernetes-sigs/kubefed/pull/1012#discussion_r296956157

Address comments from PR 1012

---

docs/installation.md

Removed outdated script reference

---

pkg/controller/dnsendpoint/common.go

**What happened:**
we have cluster A in zone A, cluster B in zone A,
now we create a federated service nginx, deploy service only in cluster A, then create a servicednsrecord associate with this federated service,  and dns endpoint will generate two zone-level endpoint with same dns name.
clusterA: nginx.default.dsj-test.svc.cn-north-7b.cn-north-7.jessiading.com:Record A: xxx.xxx.xxx.xxx
clusterB: nginx.default.dsj-test.svc.cn-north-7b.cn-north-7.jessiading.com:Record CNAME: nginx.default.dsj-test.svc.cn-north-7.jessiading.com
finally, controller will merge two endpont into one,  nginx.default.dsj-test.svc.cn-north-7b.cn-north-7.jessiading.com:Record A: xxx.xxx.xxx.xxx,nginx.default.dsj-test.svc.cn-north-7.jessiading.com
when external-dns create this endpoint in provider,  get error …

fix dns endpoint controller merged two different type record's targets with same dns name  

---

scripts/create-clusters.sh
scripts/download-e2e-binaries.sh
scripts/pre-commit.sh

@marun Created a PR to update `kind` to `v0.3.0`,  could you help review? Thx!

Update kind to v0.3.0

---

CHANGELOG.md
cmd/controller-manager/app/controller-manager.go
config/kubefedconfig.yaml
pkg/apis/core/v1beta1/defaults/defaults.go
pkg/apis/core/v1beta1/defaults/defaults_test.go
pkg/apis/core/v1beta1/validation/validation_test.go
pkg/controller/util/cluster_util.go
pkg/controller/webhook/kubefedconfig/webhook.go
pkg/features/features.go
test/common/dns.go
test/e2e/defaulting.go
test/e2e/framework/controller.go
test/e2e/framework/wait.go
test/e2e/ingressdns.go
test/e2e/leaderelection.go
test/e2e/servicedns.go

Fixes #1013.
You may choose to review a commit at a time as changes follow a fairly reasonable sequence.

Add KubeFedConfig defaulting via mutating admission webhook

---

CHANGELOG.md
docs/userguide.md
pkg/controller/sync/controller.go
pkg/controller/util/orphaninganotation.go
pkg/kubefedctl/federate/federate.go
pkg/kubefedctl/federate/util.go
pkg/kubefedctl/kubefedctl.go
pkg/kubefedctl/orphaning/disable.go
pkg/kubefedctl/orphaning/enable.go
pkg/kubefedctl/orphaning/orphaning.go
pkg/kubefedctl/orphaning/status.go
pkg/kubefedctl/util/util.go
test/common/crudtester.go

Implement orphaning-deletion commands

---

charts/kubefed/charts/controllermanager/templates/deployments.yaml
cmd/controller-manager/app/controller-manager.go
cmd/controller-manager/app/options/options.go

Fixes #795 
/assign @marun @xunpan

Set kubefed-namespace via the config mechanism for in-cluster deployment

---

pkg/controller/kubefedcluster/controller.go

controller/kubefedcluster: add handling for deletes with tombstone and prevent constant processing of cluster changes when status is updated (by caching the last observed spec and comparing on informer updates)
Related issue:
https://github.com/kubernetes-sigs/kubefed/issues/950

controller/kubefedcluster: fixes for delete handling and suppress changes due to status updates

---

CHANGELOG.md
charts/kubefed/charts/controllermanager/templates/webhook.yaml
pkg/apis/core/v1beta1/validation/validation.go
pkg/apis/core/v1beta1/validation/validation_test.go
pkg/controller/webhook/kubefedcluster/webhook.go
test/common/validation.go
test/e2e/validation.go

Validation for KubeFedCluster API

---

CHANGELOG.md
docs/userguide.md
pkg/kubefedctl/federate/federate.go
pkg/kubefedctl/orphaning/disable.go
pkg/kubefedctl/orphaning/enable.go
pkg/kubefedctl/orphaning/orphaning.go
pkg/kubefedctl/orphaning/status.go
pkg/kubefedctl/util/util.go

Resolve target namespace from the client kubeconfig context

---

pkg/controller/federatedtypeconfig/controller.go
test/e2e/ftccontroller.go

working on test cases
Fixes #815

when ftc target version changed, sync controller should be refreshed

---

pkg/controller/kubefedcluster/clusterclient.go
pkg/controller/kubefedcluster/controller.go

event for kubefedcluster

---

test/e2e/validation.go

~~**NOTE:** This PR is not reviewable until #1027 is merged.~~

Generalize validation e2e tests for each validating resource type

---

pkg/controller/sync/status/status.go

- remove unused type
- Ensure last transition time matches last probe time

Cleanup generic status handling

---

scripts/create-clusters.sh
scripts/download-e2e-binaries.sh

Handle a todo item.
Fixes #
https://github.com/kubernetes-sigs/kind/issues/111
/cc @font 
```release-note
```

Update to use Kind v0.4.0 and remove a todo

---

pkg/controller/sync/accessor.go

Add an error event when name and namespace of federatednamespace
are not same.
Fixes #1037
```release-note
```

Add Error Event for FederatedNamespace

---

pkg/kubefedctl/join.go

Get current context in kubeconfig when host-cluster-context
is not set during kubefedctl join
**Which issue(s) this PR fixes**
Fixes https://github.com/kubernetes-sigs/kubefed/issues/1064
```release-note
```

Get curretContext when host-cluster-context is empty

---

pkg/kubefedctl/enable/enable.go

Fixes #747
```release-note
```

check if federated type is referred by an existing FTC

---

scripts/fix-ca-for-k3s.sh

update comment in the script for k3s v0.7.0
Fixes #
```release-note
```

fix-ca-for-k3s.sh: document that k3s v0.7.0 no longer needs this

---

pkg/apis/core/v1beta1/validation/validation_test.go
test/common/validation.go
test/e2e/validation.go

~~**Note:** This PR is not reviewable until #1040 merges.~~
Fixes #944

Add KubeFedConfig validation e2e test

---

charts/kubefed/charts/controllermanager/templates/crds.yaml
pkg/apis/core/v1beta1/federatedtypeconfig_types.go

Adds a short name `ftc` to `federatedtypeconfig` which is easier to type in command line.
Fixes #

Add a shortname to federatedtypeconfig

---

docs/releasing.md
scripts/build-release-artifacts.sh
scripts/build-release.sh
scripts/create-gh-release.sh
scripts/util.sh

This PR adds a couple of scripts for building and verifying a KubeFed release; creating a PR with the release changes and creating a GitHub draft release. It also updates the release instructions for executing them. This helps further automate the releases of KubeFed.
Fixes #813 
Commits can be reviewed individually.

Add scripts to help automate KubeFed releases

---

README.md

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Issue #1104 Adding communication channel information to the README

---

docs/development.md

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
Fixed a broken link in  https://github.com/kubernetes-sigs/kubefed/blob/master/docs/development.md#adding-a-new-api-type

Fixing broken link in development.md

---

pkg/schedulingtypes/plugin.go

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Fixing an unnecessary type conversion

---

CHANGELOG.md
pkg/schedulingtypes/plugin_test.go

This PR is a follow-up to #1089 to ensure test coverage of the changed code and capture details about the fix in the changelog.

Add unit testing for pkg/schedulingtypes/updateOverridesMap

---

cmd/controller-manager/app/controller-manager.go

This PR makes sure, the KubeFedConfig's Spec.Scope is updated everytime the controller-manager pod is started irrespective of whether the KubeFedConfig exists or not.
Fixes # Bugzilla: [1741478](https://bugzilla.redhat.com/show_bug.cgi?id=1741478)

The DEFAULT_KUBEFED_SCOPE env var was only being set the first time the KubeFedConfig didn't exist

---

pkg/controller/util/federated_informer.go

Cluster client creation triggers rest discovery against the target cluster.  To reduce client creations, a cache has been added to federatedInformerImpl.  The cache is populated as cluster clients are used and kubefedcluster deletes clear the cached client corresponding to that cluster.

controller/util: maintain a cache of cluster clients to reduce rest discovery

---

pkg/kubefedctl/enable/deprecatedapis.go
pkg/kubefedctl/enable/deprecatedapis_test.go
pkg/kubefedctl/enable/enable.go

the equivalent APIs should be enabled at most once

---

pkg/kubefedctl/federate/util.go

PR#1118 added an incorrect way to skip federating resources that
don't comply with the DNS-1123 subdomain naming convention.
This PR fixes the issue the correct way.

Skip resources that don't have a valid DNS-1123 Subdomain name

---

docs/development.md
pkg/controller/sync/accessor.go
pkg/controller/sync/controller.go
pkg/controller/sync/dispatch/checkunmanaged.go
pkg/controller/sync/dispatch/managed.go
pkg/controller/sync/dispatch/unmanaged.go
pkg/controller/sync/resource.go
pkg/controller/util/federated_informer.go
pkg/controller/util/naming.go
pkg/kubefedctl/join.go
test/common/crudtester.go
test/e2e/e2e.go
test/e2e/framework/framework.go
test/e2e/framework/test_context.go
test/e2e/scale.go

Please see the doc changes and code comments for how this is accomplished. Note that the PR consists of a commit that refactors the sync controller to allow its behavior to be changed in support of the test, and another to implement the test.

Add test to simulate control plane behavior for large numbers of clusters 

---

pkg/controller/doc.go
pkg/controller/util/naming.go
pkg/doc.go
test/e2e/federate.go

You can see some issues on https://goreportcard.com/report/github.com/kubernetes-sigs/kubefed
Fixes #
Cleanup some code issues of gofmt and misspell

Cleanup some code issues of gofmt and misspell

---

OWNERS

This PR adds Jimmi to the OWNERS file, since he has generously agreed to pick up development / maintenance of kubefed.

Add jimmidyson to OWNERS

---

OWNERS

Adds hector as a top-level owner.

Add hectorj2f to OWNERS

---

docs/userguide.md

**What this PR does / why we need it**: It fixes a typo in the documentation. Specifically a command.
Fixes #

typo: changing 'federeate' for 'federate'

---

.travis.yml

It seems we have adopted to Go Module, so comments in Travis configuration is outdated.
Fixes #
I'm going through `kubefed` recently, I wish I can help to make it better.

Cleanup travis config about dep

---

CHANGELOG.md
charts/index.yaml

New release v0.3.0 with all the bug fixes and improvements.

Update repo for release v0.3.0

---

charts/kubefed/charts/controllermanager/crds/crds.yaml
pkg/apis/scheduling/v1alpha1/replicaschedulingpreference_types.go

Adds a short name `rsp` to `replicaschedulingpreference` which is easier to type in command line.
Fixes #

Add a shortname to replicaschedulingpreference

---

README.md

As a newbie to kubefed, it's not easy to start playing around with
kubefed due to the plethora of options on how to deploy it in the user
and development guides. Thus, an opinionated quickstart guide will
help newcomers get up and running in a jiffy.
no issue

chore: Add quickstart guide

---

OWNERS
docs/OWNERS

Remove self from OWNERS

---

pkg/controller/servicedns/controller.go

Display more clear logs.
Fixes #1285 

fix issue #1285

---

charts/kubefed/charts/controllermanager/crds/crds.yaml
scripts/sync-up-helm-chart.sh

CRD generation was broken because the script did not copy across the generated CRDs to the correct final location. At the same time as fixing that, I've taken the opportunity to ensure that the specified version of controller-gen is used to ensure we do not have issues caused by different versions of controller-gen causing hard to diagnose conflicts.

Fix up CRD generation

---

OWNERS

This PR adds @makkes as a reviewer. @makkes has been reviewing PRs for a while, as well as submitting a number of PRs that have been merged.

New reviewer: makkes

---

cmd/webhook/app/webhook.go
cmd/webhook/main.go

Signed-off-by: Alex Yang <yangyang1@zte.com.cn>
Fixes #

Fix webhook cmd

---

pkg/controller/util/podanalyzer/pod_helper.go
pkg/controller/util/podanalyzer/pod_helper_test.go
pkg/schedulingtypes/replicascheduler.go

Fixes #
Fixes https://github.com/kubernetes-sigs/kubefed/issues/1369
~~I will probably update relevant unit tests also, in a short while.~~
Updated unit tests.

Replica rebalance reconciliation fix

---

docs/development.md

development document is good for reference during development work. Keeping it correct helps contributors.
1. upgrade kubebuilder version
2. remove `--v` `-v` because it is not the valid arguments.
This is found during development. No need an extra issue.

correct command line example for test

---

cmd/controller-manager/app/controller-manager.go

Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
Fixes #

cmd/controller-manager: optimize code

---

pkg/controller/kubefedcluster/controller.go
pkg/controller/sync/controller.go

Add more error logs for `sync controller` & `kubefedcluster controller`, which can be useful to debug.
Fixes #1407

Add more error logs for sync controller & kubefedcluster controller

---

.github/workflows/build-and-test.yml
.github/workflows/test-and-push.yml
Makefile
README.md
docs/releasing.md
scripts/build-release.sh

Remove last vestiges of travis and fix release process for Github Actions
Fixes #

Remove last vestiges of travis and fix release process for Github Actions

---

README.md

The README.md says that the project is an alpha version, while since version v0.1.0 it is a beta version.

docs: update README.md to reflect current projectstate

---

Makefile
hack/verify-errpkg.sh
pkg/controller/kubefedcluster/clusterclient.go
pkg/kubefedctl/federate/util.go
pkg/schedulingtypes/replicascheduler.go
scripts/download-binaries.sh

Upgrades helm to 3.6.0 and golangci-lint to 1.40.1, satisfying the updated linters as required.
Fixes #

Upgrade golangci-lint and helm

---

scripts/create-gh-release.sh

Fixes the create release script to add asset files correctly via `gh` CLI.
Fixes #

build: Properly add asset files to github release

---

test/e2e/scheduling.go

The test on `master` after the last PR push seems to be failing because of a test flake. This PR fixes that
Ref: https://github.com/kubernetes-sigs/kubefed/runs/5593998914?check_suite_focus=true
Fixes #
Test fix

Handle possible conflict in updating test labels on cluster

---

pkg/controller/util/cluster_util.go

Fix controller-manager panic when kubeconfig set filed `insecure-skip-tls-verify` to `true`.
Fixes #1504 

fix: controller-manager panic when kubeconfig set filed insecure-skip-tls-verify

---

pkg/controller/util/worker.go
pkg/metrics/metrics.go

Controller runtime provides some [useful metrics for controllers](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/metrics/metrics.go). However, since KubeFed does not directly use controller runtime to build controllers (for some "federated" reasons), it lacks these standard metrics. This PR introduces these metrics to KubeFed and deprecates some old non-standard ones.

Introduce standard controller runtime metrics

---

docs/userguide.md

fixes #1454: add document for intersectWithClusterSelector
