kubernetes-sigs/kubefed

- test/common/util.go
- test/e2e/crud.go
- test/e2e/e2e.go
- test/e2e/e2e_test.go
- test/e2e/framework/cleanup.go
- test/e2e/framework/framework.go
- test/e2e/framework/ginkgowrapper/wrapper.go
- test/e2e/framework/logger.go
- test/e2e/framework/managed.go
- test/e2e/framework/test_context.go
- test/e2e/framework/unmanaged.go
- test/e2e/framework/util.go
- test/integration/crud_test.go
- test/integration/framework/controller.go
- test/integration/framework/crapi.go
- test/integration/framework/etcd.go
- test/integration/framework/fedapi.go
- test/integration/framework/federation.go
- test/integration/framework/kubeapi.go
- test/integration/framework/logger.go
- test/integration/framework/secureconfig.go
- test/integration/framework/util.go
This PR adds a crud e2e test that can run against both test-managed and previously deployed federations.  The semantics of invocation against deployed federation are consistent with how kube does it, e.g.
```
cd test/e2e && go test -v --kubeconfig=/path/to/kubeconfig
```
If ``--kubeconfig`` is not provided, the e2e suite will target a test-managed federation.  This duplicates how integration tests are run, but allows for future variation in the implementation of a test-managed federation (e.g. deploy using kubeadm using dind or hollow nodes).
cc: @font
> Add crud e2e

- pkg/controller/sync/controller.go
- pkg/controller/util/cluster_util.go
- pkg/controller/util/deletionhelper/deletion_helper.go
- pkg/federatedtypes/namespace.go
- test/common/crudtester.go
- test/e2e/crud.go
- test/e2e/framework/framework.go
- test/e2e/framework/managed.go
- test/e2e/framework/unmanaged.go
- test/integration/framework/federation.go
- test/integration/framework/kubeapi.go
- Changes to support`PropagatedVersion` for namespaces.
- Adds crudtester check for primary cluster so that we can run E2E tests with or without the host cluster being part of the federation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marun/federation-v2/49)
> PropagatedVersion changes to support namespaces

- pkg/controller/sync/controller.go
I traced #64 to the version cache.  I'll pursue a proper fix on Monday, but disabling the check for namespaces fixes the problem (at the cost of potentially performing some unnecessary updates).
cc: @font @onyiny-ang
> Workaround ns version handling issue

- .gitignore
- scripts/delete-federation.sh
- scripts/deploy-federation.sh
- scripts/download-binaries.sh
- scripts/pre-commit.sh
- scripts/util.sh
The included scripts automate deployment and deletion of a federation (cr api + fedv2 api + fedv2 controllers) that was documented in #36.  The active kubectl context is targeted, so theoretically this will work with more than just minikube, but it's only been tested with minikube.
> Add deployment script

- pkg/apis/core/v1alpha1/federatedcluster_types.go
- pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedcluster.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/federatedcluster.go
- pkg/client/informers/externalversions/core/v1alpha1/federatedcluster.go
- pkg/client/informers/externalversions/core/v1alpha1/interface.go
- pkg/client/listers/core/v1alpha1/expansion_generated.go
- pkg/client/listers/core/v1alpha1/federatedcluster.go
- pkg/controller/federatedcluster/controller.go
- pkg/controller/util/federated_informer.go
- pkg/kubefnord/join.go
- test/e2e/framework/unmanaged.go
- test/e2e/servicedns.go
- test/integration/framework/federation.go
- test/integration/replicaschedulingpreference_test.go
- test/integration/servicedns_test.go
This is to align with the switch of cluster-registry's Cluster resource's scope.  FederatedCluster resources will be stored in the `federation-system` namespace (where the secrets holding the auth credentials for the clusters are already stored).
Fixes ~#107~ #110.
> Change scope of FederatedCluster to be Namespaced

- pkg/kubefnord/join.go
> Do not need namespace for clusterrole and clusterrolebindings.

- cmd/kubefed2/kubefed2.go
- docs/userguide.md
- pkg/kubefed2/join.go
- pkg/kubefed2/kubefed2.go
- pkg/kubefed2/options/options.go
- pkg/kubefed2/util/util.go
- pkg/kubefed2/version.go
- scripts/deploy-federation.sh
- scripts/pre-commit.sh
The version naming is suggestive and intended to trigger comments.
> Rename kubefnord to kubefed and implement simple kubefed version

- .travis.yml
- scripts/deploy-federation.sh
- scripts/download-binaries.sh
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
This updates the pre-commit CI job. It continues to run integration tests but now runs [unmanaged](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/development.md#unmanaged-and-hybrid-cluster-setup) instead of [managed](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/development.md#managed) e2e tests i.e. a single minikube k8s cluster.
This works because we are requesting an Ubuntu 16.04 distro (Xenial) from Travis in order to use systemd. This distro is not actually documented in Travis, but appears to be available as an experimental feature.
> Enable CI e2e job against single minikube cluster

- cmd/controller-manager/main.go
- pkg/controller/replicaschedulingpreference/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/schedulingtypes/adapters/deployment.go
- pkg/schedulingtypes/adapters/interface.go
- pkg/schedulingtypes/adapters/replicaset.go
- pkg/schedulingtypes/interface.go
- pkg/schedulingtypes/plugin.go
- pkg/schedulingtypes/replicascheduler.go
- pkg/schedulingtypes/resources.go
- pkg/schedulingtypes/typeregistry.go
- test/integration/framework/controller.go
Updated and refactored to enable the same controller usage for other schedulers (am working on JobSchedulingPreferences)
@kubernetes-sigs/federation-wg
> Refactor scheduling

- docs/development.md
- docs/userguide.md
- example/sample1/federateddeployment-template.yaml
- example/sample1/federatedservice-placement.yaml
- example/sample1/federatedservice-template.yaml
- hack/install-latest.yaml
- pkg/controller/federatedcluster/controller.go
- scripts/deploy-federation.sh
- test/e2e/e2e_test.go
- vendor/k8s.io/cluster-registry/cluster-registry-crd.yaml
- Increase the memory request and limits for the federation-controller-manager.
- Add a federated service example config and update the userguide.
- Update Cluster Registry CRD for use in k8s 1.10. See https://github.com/kubernetes/kubernetes/issues/65293 for more details.
- Add client auth plugins for public cloud providers in order to run e2e tests.
> Increase mem resources for fed controller, add federated service example, other misc. changes

- test/e2e/framework/util.go
The previous `SingleCallTimeout` value of `30s` appears to be too low, as evidenced by the increasing incidence of CI jobs failing with timeout failures since e2e tests have started executing against unmanaged fixture.
> Bump e2e poll timeout to account for unmanaged fixture on travis

- docs/userguide.md
- hack/install-latest.yaml
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
- pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_federatedtypeconfig.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/federatedtypeconfig.go
- pkg/client/informers/externalversions/core/v1alpha1/federatedtypeconfig.go
- pkg/client/informers/externalversions/core/v1alpha1/interface.go
- pkg/client/listers/core/v1alpha1/expansion_generated.go
- pkg/client/listers/core/v1alpha1/federatedtypeconfig.go
- pkg/controller/federatedtypeconfig/controller.go
- scripts/deploy-federation.sh
- test/common/crudtester.go
- test/e2e/crud.go
- test/e2e/framework/unmanaged.go
- test/integration/framework/federation.go
This is the next step in allowing the fedv2 control plane to run in an arbitrary namespace (#197).  As part of this PR I updated the CRD e2e test to support targeting multiple clusters to ensure this change can be tested against the default managed fixture which uses 2 clusters.
> Update FederatedTypeConfig to be namespace-scoped

- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
Previously, the pluralName function would only add 'es' to
strings with an 's' suffix. Adding 'es' should be used for
additional suffixes. This will prevent improper pluralization
of future supported types. See:
https://howtospell.co.uk/adding-es-plural-rule
Fixes Issue: #219
> Extends Pluralization Support

- test/e2e/framework/util.go
Deployments have the most complex workflow of the existing kubernetes types, and the interaction of the deployment controller with the sync controller is likely to case the deployment crud test to take longer than for other types.  Since the deployment crud test has been regularly flaking, the previous timeout was likely not long enough.
Targets #214
> Bump e2e timeout to avoid deployment e2e timeout

- scripts/delete-federation.sh
Previously, federated config types were not being deleted by
`delete-federation.sh`. This is because a namespace was not
being provided in the `kubectl` delete command. This commit
adds the ns to the kubectl command to properly delete the
federated config type resources.
Fixes Issue: #227
> Fixes Delete Bug in Delete Script

- hack/install-latest.yaml
Update install-latest.yaml to reflect four changes:
1) Upgrade Kubebuilder to 1.0.0
2) New CRD for federatedingresses.core.federation.k8s.io and federatedingressplacements.core.federation.k8s.io
3) New CRD for dnsendpoints.multiclusterdns.federation.k8s.io
I created this file via the following command
```
kubebuilder create config --controller-image quay.io/kubernetes-multicluster/federation-v2:latest  --name federation
```
/cc @marun @shashidharatd
> Updated install-latest.yaml.

- scripts/pre-commit.sh
- test/e2e/crud.go
- test/e2e/framework/framework.go
- test/e2e/framework/test_context.go
- test/e2e/framework/unmanaged.go
- test/e2e/framework/util.go
This will allow a short default timeout for developers and CI can set a long timeout to avoid timeout flakes.
> Enable e2e test timeout to be configured

- .gitignore
/config is a an artifact from the previous use of `apiserver-builder` and should be removed.
/cc @font
> Remove /config from .gitignore

- hack/install-latest.yaml
Reverted the update that made `FederatedTypeConfig` namespace scoped in order to continue working with the latest stable released version of fedv2 (v0.0.1). This allows the userguide to continue working as expected.
Fixes #232.
/cc @pmorie
> Update install-latest.yaml to work with latest image

- pkg/kubefed2/join.go
- pkg/kubefed2/unjoin.go
- pkg/kubefed2/util/util.go
This PR cleans up role and binding creation by separating out the common healthz rule into a new role.  The existing methods are cleaned up for consistency.
This is in response to a comment from @irfanurrehman: https://github.com/kubernetes-sigs/federation-v2/pull/215#discussion_r211552117
> kubefed: clean up role and binding creation

- pkg/kubefed2/join.go
- pkg/kubefed2/options/options.go
- test/e2e/framework/test_context.go
This is for consistency with --add-to-registry as per a request by @font: https://github.com/kubernetes-sigs/federation-v2/pull/213#discussion_r211833990
> Rename --cluster-namespace to --registry-namespace

- docs/development.md
- docs/userguide.md
- scripts/download-binaries.sh
- scripts/generate-install-yaml.sh
Kubebuider v1.0.3 is shipping with Kubernetes 1.11, there is no need
to download the v1.11 kube-apiserver in test script, and also no need
to update `hack/install.yaml`, as the issue https://github.com/kubernetes/kubernetes/issues/65293
was already fixed in kubernetes v1.11.
/cc @marun @pmorie
> Upgrade Kubebuilder to v1.0.3.

- pkg/controller/util/placement.go
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
- test/common/crudtester.go
- test/common/fixtures/deployment-override.yaml
- test/common/fixtures/deployment-template.yaml
- test/common/fixtures/job-template.yaml
- test/common/fixtures/replicaset-override.yaml
- test/common/fixtures/replicaset-template.yaml
- test/e2e/framework/util.go
2 commits target #214
- Fix crudtester check of placement change when the host cluster is joined to itself.
- Fix case of placement field `clusterNames`
The remaining commits speed up test execution:
- Change replicaset and deployment e2e fixture to use replicas=1 with an override of replicas=2 (previously was 3 and override of 5).
- Change replicaset, deployment and job e2e fixture to use <2mb `busybox` image (previously was 100mb `nginx` image).
- Reduce poll and wait intervals
> Improve e2e reliability

- docs/userguide.md
- example/sample1/federatednamespace-placement.yaml
- pkg/controller/sync/controller.go
`FederatedNamespacePlacement` becoming namespace-scoped has resulted in the user guide example not working. Specifically, the resources all get created successfully, but when you try to remove `cluster2` from the `FederatedNamespacePlacement` object, the resources in the `test-namespace` are not removed because the `test-namespace` is never removed.
This was caused by mismatching keys to retrieve `Namespace` and `FederatedNamespacePlacement` objects from the cache. This is a temporary fix as `Namespaces` are the only resources we currently support whose template is cluster-scoped while the placement is namespace-scoped. A proper long-term solution should be investigated, especially when we begin to support more cluster-scoped resources.
> Fixes for namespace-scoped federatednamespaceplacement

- cmd/controller-manager/main.go
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/sync/controller.go
- scripts/delete-federation.sh
- scripts/deploy-federation.sh
This PR limits the permissions of the federation service account to a role binding when run in namespaced mode.  For some reason the `cluster-admin` roles is required - `admin` or `edit` do not grant sufficient access.
Supporting limited authz required rewriting the controller for `FederatedTypeConfig`.  The `kubebuilder` controller framework didn't appear to have any provision for limiting informer scope, so this PR rewrites the controller to be consistent with all the other federation controllers.
Targets #197
> Ensure control plane can run with only authz for the federation namespace

- pkg/controller/util/federated_informer.go
- test/e2e/e2e.go
- test/e2e/framework/unmanaged.go
- test/integration/framework/cluster.go
- test/integration/framework/federation.go
Previously cluster readiness checks were performed only for unmanaged e2e fixture and were performed on every request for clients from the fixture.  This PR ensures that readiness checks are performed once on fixture setup and for both managed and unmanaged fixture.
> Cleanup e2e readiness

- pkg/apis/core/common/util.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/version.go
`PropagatedVersion` handling was previously spread all over the sync controller, and relied upon the API and an informer to manage state.  This PR extracts that code into a new `PropagatedVersionManager` type that encapsulates version management to minimize the knowledge required by the sync controller.  The version manager manages runtime state in-memory, and caches to the API to minimize updates to target clusters across sync controller restart. 
This work is related to #60, and inspired by @danehans.  Federation of cluster-scoped types will require support for cluster-scoped PropagatedVersion, and the first step towards that goal is allowing the implementation of version management to vary.
> Factor propagated version handling out of the sync controller

- pkg/controller/sync/controller.go
- pkg/controller/util/overrides.go
- test/common/crudtester.go
Previously there was no testing of overrides being applied in integration and e2e testing.  As part of this PR, the marshaling of overrides was refactored for reuse.
Targets #255
> Add check of application of overrides to the crudtester

- cmd/controller-manager/main.go
- scripts/generate-namespaced-install-yaml.sh
As per a [PR comment](https://github.com/kubernetes-sigs/federation-v2/pull/216#discussion_r212668792) from @pmorie, the controller manager should accept arguments set via the downward api from the command line rather than as environment variables.
> Fix controller manager to only accept args from command line

- scripts/pre-commit.sh
> Enable -ginkgo.trace for ci testing

- example/sample1/federatedserviceaccount-placement.yaml
We have replaced `clusternames` to `clusterNames` for placement policy
in https://github.com/kubernetes-sigs/federation-v2/pull/260 , the
federated serviceaccount placement policy should also be updated.
Fixed https://github.com/kubernetes-sigs/federation-v2/issues/280
/cc @font @marun
> Use `clusterNames` for federated serviceaccount placement.

- test/common/dns.go
- test/common/typeconfig.go
- test/e2e/crud.go
- test/e2e/framework/framework.go
- test/e2e/ingressdns.go
- test/e2e/servicedns.go
Previously the dns tests created (and attempted to cleanup) the test namespace in member clusters.  This commit updates the tests to rely instead on the namespace sync controller to ensure resiliency.
This change was motivated by test failures noticed while working on #284.
> Use namespace sync controller in the dns tests

- pkg/kubefed2/join.go
We should use `%v` not `%s` to log bool value.
Before fix: limited-scope: %!s(bool=true)
After fix: limited-scope: true
/cc @marun
> Fixed a log issue for join.

- docs/userguide.md
I've faced some issues while deploying the federation v2 control plane when I missed the following command  "kubectl config use-context cluster1" and I ended up installing everything in cluster2 which is of no use.
> Added one-liner note for a command to project its importance

- docs/userguide.md
- scripts/delete-federation.sh
There are now three types for install federation:
- install-latest.yaml
- install.yaml
- install-namespace.yaml
We need to make sure the delete script can handle all of the cases.
/cc @marun @font 
This is a follow up for PR https://github.com/kubernetes-sigs/federation-v2/pull/290#pullrequestreview-159342381
> Enabled delete federation can delete hack/install.yaml

- pkg/controller/federatedtypeconfig/controller.go
- scripts/deploy-federation.sh
@font (offline) and @gyliu513 (in a [comment](https://github.com/kubernetes-sigs/federation-v2/pull/283#discussion_r221222183)) both noticed that a sync controller was being launched for namespaces when the control plane was running namespaced.  This isn't desirable since a namespaced control plane shouldn't require permission to list namespaces.
Previously the only check against running a sync controller for namespaces was in the deployment script not applying the type config for namespaces if deploying a namespaced control plane.  Since helm deployment is now an option, it's necessary to move the check to code so it can be shared.
> Avoid starting a namespace sync controller for namespaced federation

- test/e2e/framework/framework.go
- test/e2e/framework/managed.go
- test/e2e/framework/test_context.go
- test/e2e/framework/unmanaged.go
Otherwise any failed test runs that leave federation primitives in a persistent test cluster may impact future test runs when running with in-memory controllers.
It is still possible to debug in-memory controllers that target the entire cluster by passing `-limited-scope-in-memory-controllers=false` to test invocation.
> Target in-memory controllers in e2e at the test namespace

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/ingressdns/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/controller/servicedns/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/util/worker.go
This was motivated by needing the same code for #276.  Likely there will be further convergence in the future if not a switch to kubebuilder-based controllers if we can work with them to get the features we need.
> Refactor all controllers to use the same async worker code

- pkg/controller/federatedtypeconfig/controller.go
Not sure how this happened. After the recent pr merge the master has this compilation issue. tide did not trigger another build before merge.
https://travis-ci.org/kubernetes-sigs/federation-v2
/cc @marun @font @irfanurrehman
> Fix compilation issue

- README.md
This PR adds additional context for the concepts diagram. My intent is to make this part of the readme slightly more useful. As a next step, I'll expand this into a doc in the docs directory in a subsequent PR.
> Expand on foundational concepts in README

- test/common/crudtester.go
Previously the crudtester was retrieving the `PropagatedVersion` for a resource once and then checking that target resources matched.  In cases where target resources were updated by a controller other than
the sync controller (e.g. deployments/jobs/replicasets) in the member clusters, this created a race between the crudtester and the other controller.  This commit updates the crudtester to retrieve the `PropgatedVersion` on every iteration of the wait loop to remove the possibility of a race condition.
Fixes #214 (for real this time)
> Fix crudtester version retrieval

- scripts/pre-commit.sh
This should flush out unexpected test dependencies.
Reference: https://onsi.github.io/ginkgo/#the-spec-runner
> Randomize order of test execution in ci

- pkg/controller/sync/version/adapter.go
- pkg/controller/sync/version/manager.go
- pkg/controller/sync/version/namespaced.go
The `meta` package has methods for generically iterating over arbitrary list types, which removes the need for involving a type-specific adapter.
> Fix version manager iteration

- pkg/controller/sync/controller.go
- pkg/controller/sync/placement/namespace.go
- pkg/controller/sync/placement/namespaced.go
- pkg/controller/sync/placement/plugin.go
- pkg/controller/sync/placement/resource.go
- test/common/crudtester.go
- test/e2e/crud.go
- test/e2e/placement.go
In cluster-scoped federation, the namespace sync controller uses namespace placement to determine whether a namespace should appear in member clusters. If a namespace does not appear in member clusters, any resources it contains are also prevented from appearing.
Since namespace-scoped federation does not run the namespace sync controller, namespace placement would have no effect.  This PR changes that by ensuring that, for namespaced federation, placement for a given resource is the determined from the resource and namespace placement.
Fixes #298
> Support defaulting to namespace placement for namespace-scoped federation

- pkg/controller/sync/controller.go
- pkg/controller/sync/version/adapter.go
- pkg/controller/sync/version/manager.go
- pkg/controller/sync/version/namespaced.go
- test/common/crudtester.go
- test/e2e/version.go
Previously `VersionManager` was explicitly deleting version resources, but the inability to lock across cache and API modifications left open the possibility of version resources being orphaned.  This PR switches to creating `PropagatedVersion` resources with an `ownerReference` for its template, which leverages the garbage collector to ensure (eventual) removal of a given template's version resource.
> Use ownerReference to ensure PropagatedVersion removal 

- scripts/pre-commit.sh
- test/e2e/version.go
Recently merged test additions have increased the incidence of flakes considerably.  This PR will attempt to identify and fix those flakes.
> Reduce flakes in e2e testing

- test/common/crudtester.go
- test/e2e/crd.go
- test/e2e/crud.go
- test/e2e/framework/framework.go
- test/e2e/framework/managed.go
- test/e2e/framework/unmanaged.go
- test/integration/framework/federation.go
This PR cleans up the e2e test for CRD propagation in anticipation of adding support for propagation of cluster-scoped resources (#306).
> Cleanup crd test to simplify validation of cluster-scoped propagation

- pkg/apis/multiclusterdns/v1alpha1/dnsendpoint_types.go
- pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
Adds basic information about service DNS to the API godoc. Since ingress is very similar, I'll make this for DNS only for now, get the verbiage correct in this PR, and then do a follow-up PR to add godoc for ingress as well.
> Improve godoc for MultiClusterServiceDNSRecord and DNSEndpoint

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/version/adapter.go
- pkg/controller/sync/version/cluster.go
- pkg/controller/sync/version/manager.go
- pkg/controller/sync/version/namespaced.go
- test/common/crudtester.go
- test/common/testobjects.go
- test/e2e/crd.go
- test/e2e/version.go
Adds a cluster-scoped version adapter and validates propagation in e2e with a generated cluster-scoped CRD.
Fixes #306
> Support propagation of cluster-scoped resources

- cmd/controller-manager/main.go
Default values are already printed by `flag`, shown in #356.
Changed help texts:
```
$ docker run thartland/federation-v2:test --help
Usage of ./controller-manager:
..........
-federation-namespace string
The namespace the federation control plane is deployed in. (default "federation-system")
..........
-registry-namespace string
The cluster registry namespace. (default "kube-multicluster-public")
..........
```
> Remove duplicate default values in controller-manager help text

- cmd/controller-manager/main.go
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/ingressdns/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/controller/servicedns/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/util/cluster_util.go
- test/integration/framework/controller.go
- test/integration/servicedns_test.go
I have tested using negative values for the delay arguments, it works just as if the delay were set to 0 seconds.
Closes #356.
> Add flags to controller-manager to set cluster availability delays

- pkg/apis/core/typeconfig/interface.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/kubefed2/federate.go
- pkg/kubefed2/federate/disable.go
- pkg/kubefed2/federate/enable.go
- pkg/kubefed2/federate/federate.go
- pkg/kubefed2/federate/util.go
- pkg/kubefed2/join.go
- pkg/kubefed2/kubefed2.go
- test/common/testobjects.go
- test/e2e/crd.go
`kubefed2 federate` is intended to create the CRDs and FederatedTypeConfig necessary to federate a given target type.  This should remove the need to commit code to the repo to support types that are not expected to be referred to by controller code.
It will still likely make sense to include sample test fixture and examples in the tree, just not CRDs and FederatedTypeConfigs.
This code has been tested to work, but at present the CRDs are being generated without a validation schema (TODO).  Propagation still works without this.
A first pass of #60.
> Add 'kubefed2 federate' command

- example/sample1/federatedclusterrole-placement.yaml
- example/sample1/federatedclusterrole-template.yaml
- test/common/fixtures/clusterrole-template.yaml
__NOTE:__ This PR is not ready for review until https://github.com/kubernetes-sigs/federation-v2/pull/340 has merged.
Adds examples and test fixture for `FederatedClusterRole` and `FederatedClusterRolePlacement` resources using `generated.federation.k8s.io` API.
> Adds FederatedClusterRole Examples and Test Fixture 

- example/sample1/federatedclusterrolebinding-placement.yaml
- example/sample1/federatedclusterrolebinding-template.yaml
- test/common/fixtures/clusterrolebinding-template.yaml
__NOTE:__ This PR is not ready for review until https://github.com/kubernetes-sigs/federation-v2/pull/340 has merged.
Adds examples and test fixture for `FederatedClusterRoleBinding` and `FederatedClusterRoleBindingPlacement` resources using `generated.federation.k8s.io` API.
> Adds FederatedClusterRoleBinding Examples and Test Fixture

- cmd/controller-manager/main.go
- pkg/controller/dnsendpoint/ingress.go
- pkg/controller/dnsendpoint/service.go
- pkg/controller/federatedcluster/controller.go
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/ingressdns/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/controller/servicedns/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/util/controllerconfig.go
- pkg/controller/util/federated_informer.go
- pkg/schedulingtypes/interface.go
- pkg/schedulingtypes/plugin.go
- pkg/schedulingtypes/replicascheduler.go
- test/e2e/framework/managed.go
- test/e2e/framework/unmanaged.go
- test/integration/crud_test.go
- test/integration/framework/controller.go
- test/integration/framework/federation.go
- test/integration/integration_test.go
- test/integration/replicaschedulingpreference_test.go
- test/integration/servicedns_test.go
This is intended to simplify maintenance of controllers.  Inspired by an in-progress refactor of the rsp testing.
> Refactor all controllers to accept a common config struct

- docs/OWNERS
Adds `docs/OWNERS`, which most notably:
- makes @gyliu513 an approver in `docs/`
- makes @danehans a reviewer in `docs/`
Thanks a lot to both @gyliu513 and @danehans for their contributions to this area!
> Add docs/OWNERS

- cmd/controller-manager/main.go
- pkg/controller/schedulingmanager/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/schedulingtypes/interface.go
- pkg/schedulingtypes/replicascheduler.go
- pkg/schedulingtypes/resources.go
- test/integration/framework/controller.go
- test/integration/replicaschedulingpreference_test.go
Fix #349.
Make scheduler plugins with correct adapters created when corresponding
federated resource enabled in federatedtypeconfig.
/cc @irfanurrehman @gyliu513
> Run controllers based on system configuration

- docs/environments/gke.md
Alpha clusters are no longer needed since 1.11.2-gke.9 is now [GA](https://cloud.google.com/kubernetes-engine/release-notes#version-updates).
> Removes alpha clusters requirement from gke doc

- pkg/kubefed2/federate/enable.go
- pkg/kubefed2/federate/util.go
- test/e2e/crd.go
This will allow separation of defining and creating resources that enable federation of a type, and aid in automating addition of validation schema to primitive crds.
> Add option to output yaml to 'kubefed federate enable'

- test/e2e/crud.go
- test/e2e/framework/framework.go
- test/e2e/framework/managed.go
- test/e2e/framework/test_context.go
- test/e2e/framework/unmanaged.go
- test/e2e/ingressdns.go
- test/e2e/servicedns.go
Previously the e2e framework was responsible for setting and tearing down controller fixture even when it wasn't common to more than one test.  This PR moves the responsibility for setup and teardown to the tests to keep the framework simple and focused on shared utility.
> Remove test-specific setup from the e2e framework

- hack/install-latest.yaml
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
- pkg/controller/federatedtypeconfig/controller.go
Following up #345 
FederatedTypeConfig controller should set the observedGeneration in its control loop.
> Set observedGeneration in the federatedTypeConfig controller

- docs/userguide.md
- example/sample1/federatedclusterrole-placement.yaml
- example/sample1/federatedclusterrole-template.yaml
- example/sample1/federatedclusterrolebinding-placement.yaml
- example/sample1/federatedclusterrolebinding-template.yaml
- example/sample1/federatedconfigmap-override.yaml
I was trying to create the test resources using the command below:
```bash
kubectl apply -R -f example/sample1
```
and the command was failing due to the following errors:
```
Error from server (Invalid): error when creating "example/sample1/federatedconfigmap-override.yaml": FederatedConfigMapOverride.core.federation.k8s.io "test-configmap" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"core.federation.k8s.io/v1alpha1", "kind":"FederatedConfigMapOverride", "metadata":map[string]interface {}{"clusterName":"", "name":"test-configmap", "namespace":"test-namespace", "creationTimestamp":"2018-11-15T18:02:41Z", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"core.federation.k8s.io/v1alpha1\",\"kind\":\"FederatedCo …
```
> Fixed examples in the sample1 folder

- docs/userguide.md
`federation-system` should be used on install.yaml since there is a statefullset inside this config where it should having a correct permission for RBAC.
> install.yaml: fix have coherent namespace on tuto

- pkg/kubefed2/federate/disable.go
- pkg/kubefed2/federate/enable.go
- test/e2e/crd.go
This is intended to be in keeping with the output provided when creating and deleting resources with kubectl.
> Add informational output to federate subcommands

- .gitignore
- Gopkg.lock
- Makefile
- cmd/controller-manager/app/controller-manager.go
- cmd/controller-manager/app/options/options.go
- cmd/controller-manager/main.go
- cmd/hyperfed/main.go
- cmd/kubefed2/kubefed2.go
- docs/development.md
- images/federation-v2/Dockerfile
- scripts/deploy-federation.sh
- scripts/imagebuild.sh
similar to `hyperkube` command in k8s, `hyperfed` command is introduced as a wrapper for controller-manager and kubefed2 binaries. This is according to the comment in https://github.com/kubernetes-sigs/federation-v2/pull/416#issuecomment-438718379
> Introduce hyperfed command as a wrapper

- pkg/kubefed2/federate/disable.go
It shouldn't be necessary to lookup based on the target since the FederatedTypeConfig must exist for disable to function.
> Switch 'federate disable' to using explicit ftc name

- .travis.yml
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
This adds support for running CI with multiple clusters using the new tool [`kind`](https://github.com/kubernetes-sigs/kind)(kubernetes in docker). You can also run the `pre-commit.sh` script locally as well. The number of clusters is 2 by default, but you can override this if you'd like to test with a different number.
There are a few `kind` workarounds that are implemented in this PR until these issues are resolved:
https://github.com/kubernetes-sigs/kind/issues/110
https://github.com/kubernetes-sigs/kind/issues/111
https://github.com/kubernetes-sigs/kind/issues/112
https://github.com/kubernetes-sigs/kind/issues/113
Also, adding a versioned release for `kind` is still WIP (PR is at https://github.com/kubernetes-sigs/kind/pull/81). For now we have to rely on a git sha.
Lastly, this adds …
> Enable CI testing with multiple clusters using kind

- .travis.yml
- scripts/pre-commit.sh
Add option to skip download-binaries in pre-commit.sh, so that when the script is called in development environment, we need not keep downloading the binaries every time.
Also added a check to successfully build hyperfed binary.
/cc @font @marun
> Add option to skip download-binaries in pre-commit.sh

- pkg/kubefed2/federate/enable.go
- pkg/kubefed2/federate/util.go
- test/e2e/crd.go
Group will be allowed via a qualified name, e.g. `deployment.apps`.
>  Allow group and version to be specified for 'federate enable'

- .gitignore
Recent changes to rename binary name in image to hyperfed caused https://github.com/kubernetes-sigs/federation-v2/pull/326/files to push a binary image accidentally. To avoid such things happening to other authors, the binary name is added to git ignore list temporarily.
/cc @marun
> Add images/federation-v2/controller-manager to git ignore

- .travis.yml
- scripts/create-clusters.sh
- scripts/delete-clusters.sh
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
- scripts/util.sh
The following changes are implemented here to enable users to create and delete kind clusters for dev testing.
- This moves the functions that create kind clusters out of the CI script and into its own script to allow running locally for a dev workflow. Additional checks were added to prevent the script from clobbering user's existing kube config and warn about multiple `insecure-registry` configurations.
- Modify contexts to use `cluster[0-9]` to be consistent with the docs.
- Add delete clusters script.
> Add scripts for creating and deleting kind clusters

- pkg/kubefed2/federate/directive.go
- pkg/kubefed2/federate/enable.go
- pkg/kubefed2/federate/util.go
- test/common/testobjects.go
- test/e2e/crd.go
- test/e2e/version.go
This is intended to simplify the encoding of configuration for the types whose propagation will be enabled be default.
> Add support for 'federate enable' to be configured from a file

- docs/servicedns-with-externaldns.md
Adds details about required cluster type (i.e. GKE) and sample service type due to #370.
> Updates service dns doc to refer to issue 370 and gke clusters

- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types_test.go
Fixes https://github.com/kubernetes-sigs/federation-v2/issues/457
> Properly pluralizes type configs for resources ending in y

- docs/ingressdns-with-externaldns.md
IngressDNSRecord should be in the same namespace with FederatedIngress to make it work.
Currently, the doc uses default for IngressDNSRecord and uses test-namespace for FedertedIngress. It should not work.
@danehans
> IngressDNSRecord should be in test-namespace in ingressdns-with-externaldns.md

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/sync/controller.go
- test/e2e/framework/framework.go
- test/e2e/framework/managed.go
- test/e2e/framework/managed/controller.go
- test/e2e/framework/unmanaged.go
- test/e2e/placement.go
Since the namespace type config is generated as of #426, it seems wise to avoid hard-coding the api definition for namespace placement and always load it from the API.
> Always load the namespace type config from the api

- pkg/kubefed2/federate/enable.go
Sets the template pluralName field of a type config by using the name of the API resource.
> Sets type config template pluralname

- charts/federation-v2/charts/controllermanager/templates/crds.yaml
- hack/install-latest.yaml
- pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
- pkg/apis/multiclusterdns/v1alpha1/zz_generated.kubebuilder.go
- pkg/controller/dnsendpoint/service.go
- pkg/controller/dnsendpoint/service_test.go
Setting `dnsPrefix` for a `ServiceDNSRecord` causes zone/region level records to use the service name instead of `dnsPrefix`. This is by design. However, use cases exist for DNS name customization at global, region, and zone scopes. This PR introduces the `ExternalName` field to the `ServiceDNSRecordSpec` type to provide this functionality while keeping `dnsPrefix` as-is.
Fixes https://github.com/kubernetes-sigs/federation-v2/issues/329
/cc @shashidharatd
> Adds region/zone level custom naming support for ServiceDNSRecords

- scripts/pre-commit.sh
Fixes #496
@gyliu513 I'm disabling the ci check for now.  Some merges landed (without re-running their travis jobs) after the check was added and that broke master.  When I tried to fix the problem I ran into the same problems you did with apiserver version skew.  I will file an issue to capture what needs to happen for this check to be re-enabled.
> Disable helm chart check until the crds can be updated reliably

- pkg/kubefed2/join.go
- pkg/kubefed2/unjoin.go
- pkg/kubefed2/util/util.go
Rules update is specific to cluster roles and binding and not namespace roles and binding.
Fixes issue #354
> Updates clusterrole rules to include all NonResourceURLs

- pkg/kubefed2/federate/schema.go
`federate enable` schema generation doesn't properly handle recursive schema (it fails with a stack overflow) when attempting to enable federation for CustomResourceDefinition.  This change adds a
CRD-specific workaround to short-circuit the recursion.
Fixes #466
> Fix enabling federation for CustomResourceDefinition

- hack/install-latest.yaml
- pkg/apis/core/typeconfig/interface.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
- pkg/controller/sync/controller.go
- pkg/kubefed2/federate/disable.go
- pkg/kubefed2/federate/enable.go
- pkg/schedulingtypes/plugin.go
- test/common/crudtester.go
- test/common/testobjects.go
- test/e2e/scheduling.go
Now that overrides are generic and federation primitives are generated, there's no reason to avoid defining an override resource for a federated type.  This also ensures that all federation deployments support generic overrides regardless of whether they decide to use it initially, which is likely a win for supportability.
> Require the override field in FederatedTypeConfig

- pkg/controller/sync/version/manager.go
Since update conflicts are likely to be retried successfully, their appearance as errors in the logs is more likely to confuse users than help them.
> Log version status update conflicts as warnings rather than errors

- charts/federation-v2/charts/controllermanager/templates/crds.yaml
- charts/federation-v2/templates/deployments.apps.yaml
- charts/federation-v2/templates/jobs.batch.yaml
- charts/federation-v2/templates/namespaces.yaml
- charts/federation-v2/templates/replicasets.apps.yaml
- docs/development.md
- scripts/pre-commit.sh
- scripts/sync-up-helm-chart.sh
Fix #505 
A predownloaded kube-apiserver is started for generation federation crds
based on primitive.
@gyliu513
> automate consistent update of primitive crds

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/schedulingmanager/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/schedulingtypes/interface.go
- pkg/schedulingtypes/plugin.go
- pkg/schedulingtypes/replicascheduler.go
- pkg/schedulingtypes/typeregistry.go
Fix  #386
stop scheduling controller if federatedtypeconfig resource is deleted
from system
I also make reconcile federatedtypeconfig log V(3) to avoid messing up
default messages.
@marun
> stop scheduler and plugins if resource is deleted

- docs/userguide.md
I noticed that these sections were nested under 'Namespaced deployment' which doesn't make sense.  I'm assuming they are more properly 'higher order behaviors', though maybe a 'Networking' section would make more sense in the future.
> Move multicluster dns sections to 'higher order behaviours'

- test/e2e/version.go
Coverage is already achieved by testing cluster-scoped resources since the codepath for both is the same, and the garbage collection of namespaced resources takes an arbitrary amount of time that is not suitable for inclusion in an e2e test.
cc: @xunpan
> Skip check of owner reference addition for namespaced resources 

- pkg/controller/sync/controller.go
- pkg/controller/sync/version/manager.go
- pkg/controller/sync/version/manager_test.go
- test/common/crudtester.go
- test/e2e/version.go
Previously the resourceVersion of the template resource was used, but resourceVersion changes when status changes.  Switching to a hash paves the way to store propagated version in the status of a template resource.
Part 1 of #479
> Use a hash of the template field as the template version

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/placement/namespaced.go
- pkg/controller/sync/placement/plugin.go
- pkg/controller/sync/placement/resource.go
- pkg/controller/sync/placement/resource_test.go
- pkg/controller/util/constants.go
- pkg/controller/util/resourceclient.go
- pkg/controller/util/resourceinformer.go
- test/common/crudtester.go
- test/e2e/crud.go
- test/e2e/framework/framework.go
- test/e2e/framework/unmanaged.go
- test/e2e/ingressdns.go
- test/e2e/placement.go
- test/e2e/servicedns.go
Up till now namespace propagation in a cluster-scoped deployment was implicit - a namespace would be propagated to member clusters by default if a namespace placement resource was absent.  This PR reverses that behavior so that a namespace is not propagated if placement is absent.  This also prevents a resource from being propagated to a member cluster unless its containing namespace is configured to be propagated to that cluster.
This change is intended to ensure that federation will play nicely when deployed to existing clusters in which only a subset of available namespaces are intended to be federated.  As part of the change, finalization for federated namespaces was moved to namespace placement to prevent the sync controller from attempting to remove namespaces from member clusters …
> Require explicit namespace placement

- docs/ingress-service-dns-with-coredns.md
- docs/userguide.md
Fixed #448
Add guide for Ingress and Service DNS in minikube federation cluster
Currently, coredns has issues in handling obsolete records.  #464 is logged to trace this issue. However, it does not impact how to set up external-dns in minikube with CoreDNS.
> DNS with external-dns based on CoreDNS in minikube

- pkg/controller/sync/controller.go
- pkg/controller/sync/placement/namespaced.go
- test/e2e/placement.go
Previously namespace placement changes for namespaced resources did not properly trigger reconcile events for contained resources.
> Ensure namespace placement changes trigger useful reconcile events

- pkg/apis/core/typeconfig/interface.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/sync/accessor.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/resource.go
- pkg/controller/sync/resource_test.go
- pkg/controller/sync/version/manager.go
- pkg/controller/util/deletionhelper/deletion_helper.go
- test/common/crudtester.go
- test/e2e/version.go
This change factors the logic of federated type composition out of the sync controller and into an accessor type that creates a logical federated resource to encapsulates one or more underlying kubernetes resources.  This separation is intended to simplify future maintenance.
> Factor host cluster interaction out of the sync controller

- pkg/controller/util/overrides.go
- pkg/schedulingtypes/plugin.go
- test/common/crudtester.go
Defining a struct for generic overrides and unmarshalling via json is much simplier than using unstructured helpers.
> Simple overrides unmarshalling

- scripts/download-binaries.sh
If you are unlucky enough, "etcd --version | head -n 1" can
fail due to pipefail. (Depending on process scheduling and
other factors.)
As it's the only use of a pipe in this script, this commit
simply disables the pipefail option.
> download-binaries.sh: Remove a problematic pipefail

- pkg/kubefed2/join.go
- pkg/kubefed2/unjoin.go
> Add --host-cluster-name to kubefed2 join to override use of kubeconfig context name for resources

- scripts/pre-commit.sh
- scripts/sync-up-helm-chart.sh
Fix#589
build kubefed2 on demands with parameter control: when the script is used independently, kubefed2 should be build. If it is used in pre-commit.sh, the build process should be ignored.
@gyliu513 @marun
> build kubefed2 on demands with parameter control

- charts/federation-v2/templates/serviceaccounts.yaml
- config/enabletypedirectives/serviceaccounts.yaml
- pkg/controller/sync/controller.go
- pkg/controller/util/constants.go
Previously service account propagation had been configured to use the generation field for versioning, which was masking the need to retain the secrets field when it was populated by the in-cluster service
account controller.  Switching to the resource version field for versioning resulted in thrashing between the sync and service account controllers.  The sync controller would continually clear the 'secrets' field, and the service account controller would continually generate a new token secret and set it in the 'secrets' field.  This change ensures that the sync controller retains the 'secrets' field of service accounts to avoid this problem.
> Fix service account sync

- pkg/kubefed2/unjoin.go
- pkg/kubefed2/util/util.go
Fix#592
forcely delete federation information in the host cluster if a member cluster
is not available
> forcely delete a member cluster information in the host cluster 

- cmd/controller-manager/app/controller-manager.go
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/util/genericinformer.go
The generated clients need to be removed as a precondition to implementing HA (due to a client-go dependency), but the generic client intended to replace the generated clients does not support the watch call necessary for informers.  This commit hacks together a generic informer to work around that omission so that the generic client is a viable replacement for the generated clients.
> Implement a generic informer

- charts/federation-v2/charts/controllermanager/templates/crds.yaml
- charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
- charts/federation-v2/templates/configmaps.yaml
- charts/federation-v2/templates/deployments.apps.yaml
- charts/federation-v2/templates/ingresses.extensions.yaml
- charts/federation-v2/templates/jobs.batch.yaml
- charts/federation-v2/templates/namespaces.yaml
- charts/federation-v2/templates/replicasets.apps.yaml
- charts/federation-v2/templates/secrets.yaml
- charts/federation-v2/templates/serviceaccounts.yaml
- charts/federation-v2/templates/services.yaml
- config/enabletypedirectives/deployments.apps.yaml
- config/enabletypedirectives/ingresses.extensions.yaml
- config/enabletypedirectives/jobs.batch.yaml
- config/enabletypedirectives/replicasets.apps.yaml
- hack/install-latest.yaml
- pkg/apis/core/typeconfig/interface.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/apis/core/v1alpha1/zz_generated.kubebuilder.go
- pkg/controller/sync/controller.go
- pkg/controller/util/propagatedversion.go
- pkg/kubefed2/federate/directive.go
- pkg/kubefed2/federate/enable.go
- test/common/crudtester.go
As per a suggestion from @irfanurrehman, the field used in deriving the version of a cluster object is now determined at runtime rather than having to be configured at the type level.  This allows use of the `generation` field where an object is expected to be modified regularly by a controller, and fallback to the `resourceVersion` field if the generation field is not being set.  Removing the requirement to configure `comparisonField` when enabling federation of a type will remove the possibility of a user inadvertently choosing the wrong field and the potential for variance in type configuration across deployments of federation. 
Fixes #480
> Determine the comparison field at runtime rather than configuring

- charts/federation-v2/templates/clusterroles.rbac.authorization.k8s.io.yaml
- charts/federation-v2/templates/configmaps.yaml
- charts/federation-v2/templates/deployments.apps.yaml
- charts/federation-v2/templates/ingresses.extensions.yaml
- charts/federation-v2/templates/jobs.batch.yaml
- charts/federation-v2/templates/namespaces.yaml
- charts/federation-v2/templates/replicasets.apps.yaml
- charts/federation-v2/templates/secrets.yaml
- charts/federation-v2/templates/serviceaccounts.yaml
- charts/federation-v2/templates/services.yaml
- docs/userguide.md
- example/sample1/federatedclusterrole.yaml
- example/sample1/federatedclusterrolebinding.yaml
- example/sample1/federatedconfigmap.yaml
- example/sample1/federateddeployment.yaml
- example/sample1/federatedingress.yaml
- example/sample1/federatedjob.yaml
- example/sample1/federatednamespace.yaml
- example/sample1/federatedsecret.yaml
- example/sample1/federatedservice.yaml
- example/sample1/federatedserviceaccount.yaml
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/controller/sync/accessor.go
- pkg/controller/sync/resource.go
- pkg/kubefed2/federate/directive.go
- pkg/kubefed2/federate/enable.go
- test/e2e/crd.go
This change is in response to the unification of federation primitives into federated types.  The term 'primitives' is no longer relevant, and continuing to include it in documentation or code is likely to cause confusion.  As part of this change, the api group that federated types are generated into has been changed from `primitives.federation.k8s.io` to `types.federation.k8s.io`.  I'm not fixed on the name, but there does need to be differentiation from the `core` group, as everything in the core group is essential to propagation but the contents of the generated group are likely to depend on the propagation requirements of a federation deployment.
> Replace references to 'federation primitives' with 'federated type'

- cmd/controller-manager/app/controller-manager.go
- pkg/controller/schedulingmanager/controller.go
- test/e2e/framework/managed/controller.go
- test/e2e/framework/managed/federation.go
- test/e2e/scheduling.go
When related federatedtypeconfig resources is created, scheduler and
related plugin controllers are started. If they are deleted, stop
related scheduler and plugin controllers.
@marun any comments for related test cases?
Fixes #543
> add test case for scheduler manager

- pkg/controller/sync/placement_test.go
- pkg/controller/sync/resource_test.go
- pkg/controller/util/constants.go
- pkg/kubefed2/disable.go
- pkg/kubefed2/enable/directive.go
- pkg/kubefed2/enable/enable.go
- pkg/kubefed2/enable/schema.go
- pkg/kubefed2/enable/util.go
- pkg/kubefed2/enable/validation.go
- pkg/kubefed2/federate/disable.go
- pkg/kubefed2/federate/federate.go
- pkg/kubefed2/federate/util.go
- pkg/kubefed2/kubefed2.go
- test/common/crudtester.go
- test/common/fixtures.go
- test/common/testobjects.go
- test/common/typeconfig.go
- test/e2e/crd.go
- test/e2e/crud.go
- test/e2e/framework/managed/federation.go
- test/e2e/placement.go
- test/e2e/scheduling.go
- test/e2e/version.go
Implements `kubefed2 federate <type-name> <resource-name>`.
Follow ups:
a. Federate a namespace (needs special handling)
b. Emit federated yaml rather then creating actual federated resource
c. Fetch resource to federate from any federated cluster 
cc @marun
> Federate resource

- pkg/apis/register.go
- pkg/client/generic/genericclient.go
- pkg/client/generic/scheme/register.go
apis.Scheme is a global object.  AddToScheme to that is not
a concurrency safe operation and occasionally causes
"fatal error: concurrent map read and map write" panics
during e2e tests.
> Build a Scheme for generic client at init time

- pkg/client/generic/genericclient.go
- pkg/controller/sync/version/adapter.go
- pkg/controller/sync/version/cluster.go
- pkg/controller/sync/version/manager.go
- pkg/controller/sync/version/namespaced.go
- test/common/crudtester.go
- test/e2e/framework/unmanaged.go
- test/e2e/version.go
- The switch to the generic client voilated some of the assumptions behind version manager client usage.  This PR updates the version manager to be fully compatible with the generic client.
- The generic client will trigger race detection if a client is constructed with a shared kubeconfig object that is changed after client construction.  The most common change in the codebase is the addition of a user agent.  This PR ensures a request for a new client with a user agent is always constructed with a copied kubeconfig.
Partially addresses #623.
> Fix races in version manager and generic client construction

- scripts/deploy-federation.sh
To workaround the following error on the following invocation of
"kubefed2 enable".
customresourcedefinition.apiextensions.k8s.io/clusters.clusterregistry.k8s.io created
F0304 09:24:34.796992    2281 enable.go:111] error: Error listing api resources: unable to retrieve the complete list of server APIs: clusterregistry.k8s.io/v1alpha1: the server could not find the requested resource
> deploy-federation.sh: Wait for the propagation of clusterregistry CRD

- cmd/controller-manager/app/controller-manager.go
- cmd/controller-manager/app/leaderelection/leaderelection.go
- test/e2e/leaderelection.go
Fixes: https://github.com/kubernetes-sigs/federation-v2/issues/642
It is observed that leader election e2e test is flaky due to multiple go routines involved in the test, which results in timeout issue. This pr introduces the synchronisation between go routine methods in the test.
It is also observed that the leader election library from client-go is not concurrent safe which results in error like below:
```
WARNING: DATA RACE
Read at 0x00c000836148 by goroutine 204:
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).IsLeader()
/home/s70553/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:195 +0x7a
github.com/kubernetes-sigs/federation-v2/test/e2e.waitToBecomeLeader.func1() …
```
> Fix leader election e2e test

- Gopkg.lock
- vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
- vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
[k8s.io/kube-openapi](https://github.com/kubernetes/kube-openapi) has seen recent fixes to ensure compliance with the openapi standard.  Recent builds of openshift return openapi that reflects these fixes but that break our older vendored version of kube-openapi.  This PR updates the vendored version of kube-openapi to ensure compatibility with both openshift and future versions of kubernetes.
> Update kube-openapi to include compatibility fixes required by openshift

- charts/federation-v2/templates/deployments.apps.yaml
- charts/federation-v2/templates/replicasets.apps.yaml
- docs/userguide.md
- pkg/controller/sync/controller.go
- pkg/controller/sync/controller_test.go
- pkg/controller/util/constants.go
- pkg/kubefed2/enable/validation.go
`kubefed2 enable` is updated to add a `retainReplicas` field for target types that expose a `spec.replicas` field.  If set on a federated resource, the sync controller will attempt to retain a replicas field from the target resource when performing updates to the target.  This is intended to avoid thrashing the scheduler when in-cluster HPA is targeting a scalable resource.
The granularity of this retention is all clusters or no-clusters, with the expectation that where HPA is intended to be applied selectively, a user will define 2 resources (one with `retainReplicas: true` and one with `retainReplicas: false`) along with partitioning placement.
Fixes #570 
TODO
> Enable configurable replicas retention by the sync controller

- pkg/kubefed2/join.go
- pkg/kubefed2/unjoin.go
- pkg/kubefed2/util/util.go
In namespaced federation, make RBAC for clusterrolebinding and clusterrole name contain namespace
So that each namespaced federation has its owned RBAC.
E.g. after installation of namespaced federation in `foo` namespace.
```
$ kubectl get clusterrole  | grep fed 
federation-controller-manager:foo:healthcheck-cluster1-cluster1        15s
$kubectl get clusterrolebindings  | grep fed
federation-controller-manager:foo:healthcheck-cluster1-cluster1   23s
```
This is better than sharing clusterrole and clusterolebindings for all namespaced federation as I implemented in https://github.com/kubernetes-sigs/federation-v2/pull/617 after considering marun's advise.
This method is simple to implement and easy to maintain.
> support cluster RBAC for namespaced installation

- pkg/kubefed2/enable/enable.go
`--override-paths` was removed with the implementation of generic overrides.
> Remove invalid option from `kubefed2 enable` example

- pkg/kubefed2/enable/enable.go
check in `CreateResources` to make `dry-run` succeed even there is no namespace. It is not hard dependecy for `dry-run`
Fixes #656
> check if namespace exist or not before creating resources in federation enable

- scripts/delete-federation.sh
- scripts/pre-commit.sh
- cluster scope resource CRDs are created on demand and not deleted in delete-deployment operation to avoid breaking other namespaced federations
- an option to clean all cluster scope resources.
> support multiple namespaced federation with script

- pkg/controller/sync/resource.go
- pkg/controller/util/deletionhelper/deletion_helper.go
- test/common/crudtester.go
This commit fixes a test bug and the deletion helper bug it was masking to correct previously broken namespace deletion handling.
- Symptom: Deleting a federated namespace would not result in the removal of the namespaces it was managing in member clusters.
- Test bug: When 2 clusters (one of them the host cluster) were targeted by the crudtester's CheckPropagationChange method, the namespace in the non-host cluster would be removed.  A subsequent call to CheckDelete would automatically succeed since the namespace no longer existed in non-host member clusters.
- Deletion helper bug: The key being used to attempt retrieval of namespaces in member clusters was for the federated namespace (i.e. `<namespace>/<namespace>`) rather than the namespace that contained it (i.e. `<namespace>`). A …
> Fix namespace deletion handling

- charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
- charts/federation-v2/charts/controllermanager/templates/role.yaml
This has been breaking new users attempting to try federation.  I had assumed that the CI testing of helm would catch this sort of thing, but as per #670 that doesn't appear to be the case.
> Fix helm chart rules to allow types instead of primitives

- scripts/imagebuild.sh
In the 0.0.7 release, the binary name built in CI changed from `hyperfed` to `hyperfed-linux`. This broke the imagebuild.sh script that pushes to quay during a release; this PR makes a tactical fix to that script. Longer term, we should just run a make command to build and push the image to reduce the risk of name changes causing future breaks.
> Fix binary name break in scripts/imagebuild.sh

- test/e2e/framework/logger.go
Show where it failed in the summary, instead of always showing logger.go.
Before:
[Fail] Federated "namespaces" [It] should be created, read, updated and deleted successfully
/home/ubuntu/go/src/github.com/kubernetes-sigs/federation-v2/test/e2e/framework/logger.go:39
After:
[Fail] Federated "namespaces" [It] should be created, read, updated and deleted successfully
/home/ubuntu/go/src/github.com/kubernetes-sigs/federation-v2/test/common/crudtester.go:339
> e2eLogger: Make the summary a little more useful

- pkg/kubefed2/enable/enable.go
- pkg/kubefed2/federate/federate.go
- pkg/kubefed2/federate/util.go
- pkg/kubefed2/util/yaml_writer.go
- test/e2e/federate.go
This PR is on top of #647 
#647 commits are not reviewable here.
To make it easier for review, the enhancements are implemented in a PR chain:
> Implement -o yaml for federate resource

- charts/federation-v2/charts/controllermanager/templates/role.yaml
- scripts/deploy-federation.sh
cluster-admin is removed for the controller role binding in https://github.com/kubernetes-sigs/federation-v2/pull/673
However, namespaced permission is not set correctly to have permission to access `configmaps`, `secrets`, `events` for controller-manager functions.
I just make it has consist rule with clusterrole.
@marun
> make federation-role has enough permission for namespaced deployment

- CHANGELOG.md
- docs/userguide.md
- pkg/controller/sync/controller.go
- pkg/controller/sync/resource.go
- pkg/controller/util/deletionhelper/deletion_helper.go
- test/common/crudtester.go
- test/e2e/crd.go
- test/e2e/crud.go
- test/e2e/placement.go
fedv2 has been using the `orphan` finalizer in attempt to integrate with kube deletion policy.  This use of `orphan` proved problematic, though, since kube deletion policy is internal to a single cluster and the sync controller ends up racing with the gc (as per #622).  This PR switches to a new finalizer (`federation.k8s.io/sync-controller`) that ensures that deletion of federated resources will be visible to the sync controller and a new annotation (`federation.k8s.io/orphan`) in place of the `orphan` finalizer to indicate that managed resources should be retained on deletion of their managing federated resource.  
Documentation of the new deletion policy and use of finalizers is included, as is a test of orphan deletion (superceding that proposed by #606).
Due to the finalizer change, …
> Fix orphan deletion

- pkg/kubefed2/enable/directive.go
- pkg/kubefed2/enable/enable.go
- test/e2e/crd.go
Previously the crd e2e test was using a random group/version, but this was breaking a helm deploy that was granted only selective permissions.  Switching to the default group/version used by enable ensures the test will always have sufficient privileges to run.
This PR is now in support of #710.
> Update crd test to use a permitted group/version

- charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
- scripts/deploy-federation.sh
cluster-admin is removed for the controller role binding in #673
However,  permission is not set correctly to have permission to make controller work.
> make federation-role has enough permission for cluster-scope federation deployment

- scripts/create-clusters.sh
- scripts/delete-clusters.sh
- scripts/download-e2e-binaries.sh
Part of the fix for #699
`kind create cluster` now respects the name provided rather than always prefixing with `kind-`, so this PR has changed the way names are handled.
> Update kind to 0.2.0

- pkg/controller/sync/controller.go
- pkg/controller/sync/placement.go
- pkg/controller/sync/placement_test.go
- pkg/controller/sync/resource.go
Placement computation is updated to return a set of the selected clusters rather than slices of both selected and unselected clusters.  This is in anticipation of collapsing the current sync loops for add/update and deletion into a single sync loop.
2nd in a series targeting #612
> Simplify placement computation

- pkg/controller/schedulingpreference/controller.go
- test/e2e/framework/unmanaged.go
I noticed these when testing in hybrid mode (unmanaged + in-memory controllers), prompting me to file #718.
> Fix race conditions detected with in-memory execution of controllers

- pkg/controller/sync/version/manager.go
Previously more than one thread could potentially modify VersionManager.versions.  This PR ensures that version writes are
synchronous to avoid that possibility.
> Fix version manager race

- pkg/controller/sync/accessor.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/resource.go
- pkg/controller/sync/updater.go
- pkg/controller/util/federated_updater.go
The existing federated updater required that cluster operations be pre-computed.  This complicated the proposal to cleanly implement support for limiting the federation informers to managed resources and then adopt resources as necessary (which would involve converting an add to an update).
This PR refactors the sync controller's reconcile loop and implements a new updater to allow cluster operations to be dispatched individually.  It also ensures that reconciliation events are logged on federated resources where possible.
The current federated updater is left in place for now since the deletion helper is still using it.  Future PRs in this series are intended to rewrite the deletion helper to use the new updater and remove the old federated updater.
3rd in a series targeting #612
> Refactor sync controller reconcile loop

- charts/federation-v2/charts/controllermanager/templates/crds.yaml
- pkg/apis/core/v1alpha1/federatedcluster_types.go
I'm adding an additional column called `READY` in the federatedcluster type to print the readiness status for a cluster when you run `kubectl get federatedclusters -n federation-system` 
```
$ kubectl get federatedclusters -n federation-system
NAME         AGE           READY
cluster1     20m           true
cluster2     20m           true
```
We need to bump up the version for `kubebuilder` (probably v1.0.6/1.0.7) in order to support the`kubebuilder:printcolumn` annotation.
> Added additionalprintercolumn "Ready"  for the federatedcluster

- CHANGELOG.md
- charts/federation-v2/templates/crds.yaml
- pkg/controller/sync/controller.go
- pkg/controller/sync/resource.go
- pkg/controller/sync/resource_test.go
- pkg/kubefed2/enable/enable.go
- test/common/crudtester.go
- test/e2e/version.go
Previously the template for a FederatedNamespace namespace was sourced from the containing namespace.  This divergence from the norm of sourcing the template from a field in the federated resource was a source of user confusion.
Fixes #652 
4th in a series targeting #612
> Switch to having the FederatedNamespace define the template

- pkg/kubefed2/enable/enable.go
- pkg/kubefed2/enable/util.go
- pkg/kubefed2/federate/federate.go
- test/e2e/federate.go
> Make federate resource usable without federation API

- pkg/kubefed2/disable.go
- pkg/kubefed2/enable/enable.go
- pkg/kubefed2/federate/federate.go
- pkg/kubefed2/federate/util.go
- pkg/kubefed2/join.go
- pkg/kubefed2/unjoin.go
Follow up fixes pending from older PRs
Follow ups from :
1. [comment](https://github.com/kubernetes-sigs/federation-v2/pull/660#issuecomment-478092485).
2. [comment](https://github.com/kubernetes-sigs/federation-v2/pull/661#discussion_r270703867)
Additionally:
1. Error message in the base commands started with small  alphabet, which looked out of sync. All other messages start in caps.
2. `FederatedResourceFromTargetResource()` should not modify input.
cc @marun
> Kubefed2 Federate fixes

- scripts/create-clusters.sh
CI fails because daemon.json exists. It may be related to CI environment change. But logically, it is not good to fail if the file exists. If exists, we only need to add our own configuration instead of reporting error.
Fixes #756
> Fix CI fail when there has daemon.json already

- charts/index.yaml
The addition of a chart index detailing released versions of federation will allow the following installation workflow:
```
helm repo add fedv2-charts https://raw.githubusercontent.com/marun/federation-v2/add-chart-repo-index/charts/
helm install fedv2-charts/federation-v2 --name=federation-v2 --version=0.0.8 --namespace federation-system
```
This PR is intended to merge ahead of the update to the helm instructions proposed in #751.
> Add chart index to support installing the released chart

- scripts/delete-federation.sh
After use exact RBAC for controller and remove script based installation, the clusterrolebinding federation-admin no longer needed. Just clean it.
> clean obsolete script to delete clusterrolebinding federation-admin

- scripts/deploy-federation.sh
Allow running deploy-federation.sh when:
* There is already a working tiller installation, and the user doesn't have the ability to create cluster-wide roles.
* There are no additional specified JOIN_CLUSTERS.
> Make deploy-federation.sh more robust

- CHANGELOG.md
- pkg/controller/sync/controller.go
- pkg/controller/sync/resource.go
- pkg/controller/sync/updater.go
- pkg/controller/sync/version/manager.go
- pkg/controller/util/federated_informer.go
- pkg/controller/util/resourceinformer.go
- test/common/crudtester.go
- test/common/dns.go
- test/e2e/crud.go
This PR labels managed resources with `federation.k8s.io/managed: true` and the federated informer will only watch resources so labeled.  Existing resources will be updated to include the label, and this is implicitly tested by the crud test for namespaces (since the namespace in the host cluster exists and will be adopted).
The label will be removed from namespaces in the host cluster in the event of a propagation change resulting in the host cluster not existing in the selected set.  The label is not yet removed from a namespace in the host cluster when a FederatedNamespace is deleted.  The label is also not yet removed from an orphaned resource.  Both of these changes will be made in a subsequent PR that rewrites the deletion helper.
Fixes #549
TODO:
5th in a series targeting #612
> Only watched managed resources

- charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
- charts/federation-v2/charts/controllermanager/templates/role.yaml
The controller currently lacks the permission to patch events which causes some errors. To rectify this I've added patch to the cluster role
```
'events "test-deployment.1595eea7da7b10cc" is forbidden: User "system:serviceaccount:federation-system:default" cannot patch resource "events" in API group "" in the namespace "test-namespace"' (will not retry!)
```
> Give controller cluster role ability to patch

- Makefile
`make` will result into below below error without fix on macOS
```
cp -f bin/hyperfed-linux images/federation-v2/hyperfed
cp: bin/hyperfed-linux: No such file or directory
make: *** [container] Error 1
```
> [Makefile] fix `make` compilation error on macOS

- scripts/create-clusters.sh
This reverts a check for the docker daemon config file that was performed only on the host. Currently this breaks local testing as well as CI whenever the host's docker daemon config file already exists since this code is called from 2 different contexts: the host and the cluster. We'll need to address it differently per https://github.com/kubernetes-sigs/federation-v2/pull/764#discussion_r276029510.
> Remove host-only docker daemon config file check

- charts/federation-v2/charts/controllermanager/templates/crds.yaml
- pkg/apis/core/v1alpha1/federatedcluster_types.go
Presently if you run `kubectl get federatedcluster -n federation-system`, it will display the following o/p:
```
NAME       READY  
cluster1     True    
cluster2     True
```   
however, it should display:  
```
NAME       READY   AGE
cluster1   True    1m
cluster2   True    1m
```
The workaround here would be adding the following line 
`// +kubebuilder:printcolumn:name=age,type=date,JSONPath=.metadata.creationTimestamp` in the federatedcluster_types.go
It looks like the `printercolumn` definition is replacing the existing server-side columns(in this case it was `Age`).
> adding Age column while listing the cluster status

- CHANGELOG.md
- charts/federation-v2/charts/controllermanager/templates/crds.yaml
- pkg/apis/core/v1alpha1/federatedcluster_types.go
- pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go
- pkg/apis/multiclusterdns/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/dnsendpoint/service.go
- pkg/controller/dnsendpoint/service_test.go
- pkg/controller/federatedcluster/clusterclient.go
- pkg/controller/federatedcluster/controller.go
- pkg/controller/servicedns/controller.go
- test/e2e/servicedns.go
Fixes: https://github.com/kubernetes-sigs/federation-v2/issues/678
This PR adds additional zone level DNS record to take care of cross-cluster service discovery in case of multi-zone clusters
> Extend service discovery for multi-zone clusters

- cmd/controller-manager/app/controller-manager.go
- cmd/controller-manager/app/options/options.go
- config/federationconfig.yaml
- pkg/controller/util/cluster_util.go
Use default values in controller manager if the `FederationConfig` yaml file not specified the field.
As mentioned in #770, the configuration value used by controller will be updated to `FederationConfig`
Fixes #770
> support optional values in FederationConfig 

- docs/userguide.md
- pkg/kubefed2/join.go
- pkg/kubefed2/options/options.go
- pkg/kubefed2/unjoin.go
- scripts/delete-federation.sh
- scripts/deploy-federation.sh
`kubefed2` should configure itself with `FederationConfig`
Currently, `limited-scope` and `registry-namespace` can be get from `FederationConfig`
Fixes #748
> get option from FederationConfig instead of specified in command line

- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/dispatch/operation.go
- pkg/controller/sync/dispatch/unmanaged.go
This will enable reuse for deletion handling.  The primary difference between the 2 contexts (managed vs unmanaged) is that events cannot be recorded against a federated resource if it is marked for deletion, so logging and error handling need to be used instead.
8th in a series targeting #612
> Factor unmanaged dispatcher out of the managed dispatcher 

- CHANGELOG.md
- charts/index.yaml
- docs/releasing.md
v0.0.9 has been [released](https://github.com/kubernetes-sigs/federation-v2/releases/tag/v0.0.9).  This PR includes the supporting updates to the chart index and changelog.  I've also done a bit of cleanup on the releasing instructions and added some steps that were missing.
Please merge asap to ensure the updated chart index is available for use.
> Release v0.0.9

- CHANGELOG.md
- pkg/kubefed2/disable.go
- pkg/kubefed2/enable/directive.go
- pkg/kubefed2/enable/enable.go
- pkg/kubefed2/join.go
- pkg/kubefed2/options/options.go
- pkg/kubefed2/unjoin.go
- test/e2e/crd.go
- test/e2e/scheduling.go
With this change `kubefed2 disable` now deletes the `FederatedTypeConfig` instead of just setting `propagationEnabled` to `false`. It will also wait for the sync controller to shut down before deleting it, and optionally delete the federated type CRD as well.
Partial fix for #721.
> kubefed2 disable should delete the FTC rather than set propagationEnabled

- .travis.yml
- scripts/download-binaries.sh
- scripts/pre-commit.sh
Recently I saw a CI job that the linter failed but that still ran all the tests.  I realized that travis runs script entries in parallel, which isn't the behavior we want, and also that instructions included in `.travis.yml` aren't easy for developers to reuse.  That prompted me to make the following changes to ensure our ci job fails fast on low-cost tests and is easier to reproduce locally:
- moved the download and execution of `golangci-lint` to the `pre-commit.sh` script
- moved the execution of the boilerplate check to `pre-commit.sh`
I also updated the version of helm to the latest and removed some unnecessary log output.
> Cleanup ci script

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/schedulingmanager/controller.go
- scripts/pre-commit.sh
- test/e2e/framework/controller.go
- test/e2e/scheduling.go
This PR has the following changes:
- Reverts a change to add/remove finalizers when a `FederatedTypeConfig` is created/deleted.
- Fixes `FederatedTypeConfig` status to set the correct current status.
- Fixes E2E tests associated with `FederatedTypeConfig` finalizer changes.
- Fixes race conditions associated with the `FederatedTypeConfig` controller.
> Fix issues with FederatedTypeConfig controller

- charts/federation-v2/README.md
I attempted to follow the helm install guide but against a kind cluster helm lacked the permissions necessary to deploy the chart. The deploy script was working, which suggested the need to update the install guide to include creation of the privileged service account as per the script.
> Document how to configure helm rbac

- charts/federation-v2/charts/controllermanager/templates/clusterrole.yaml
- charts/federation-v2/charts/controllermanager/templates/role.yaml
- charts/federation-v2/charts/controllermanager/templates/rolebindings.yaml
A new role for leader elector is created in federation controller namespace for bindings.
`secret` and `configmap` has minimum privilege
Fixes #687
> namespaced leader elector RBAC for cluster scope federation

- CHANGELOG.md
- pkg/controller/sync/accessor.go
- pkg/controller/sync/controller.go
- test/common/crudtester.go
- test/e2e/crud.go
This PR ensures that the managed label (`federation.k8s.io/managed: true`) is removed from orphaned resources or namespaces in the host cluster or when a managed resource is seen without a corresponding federated resource. 
Fixes #612
> Ensure managed label is removed from unmanaged resources

- pkg/kubefedctl/join.go
Fixes #733.
This PR allows the user to have RBAC permissions to the namespaced installation host, but not clusterwide access.  Clusterwide access is still required to join other clusters.
I use this successfully to create federations between my local, namespace-only role, and remote clusterwide roles.
> Don't fail without cluster scope.

- CHANGELOG.md
- pkg/apis/core/typeconfig/interface.go
- pkg/apis/core/v1alpha1/federatedtypeconfig_types.go
- pkg/controller/federatedtypeconfig/controller.go
~~**NOTE**: This PR is not reviewable until #821 merges.~~
This change modifies the `FederatedTypeConfig` controller to start/stop all enabled namespaced sync controllers if the namespace `FederatedTypeConfig` resource is created/deleted. It will also fail to start any namespaced sync controller if the namespaced `FederatedTypeConfig` resource does not exist.
This also reverts a change to add and remove a finalizer for the FTC, requiring some E2E test changes, and discovering a couple race conditions along the way.
As a future follow-up soon, I will refactor the FTC controller, particularly the `reconcile` method.
Fixes #722
Edited:
I think we should add E2E tests for the FTC controller in the near future.
> Removal of the FederatedTypeConfig for namespaces disables all namespaced sync controllers

- docs/userguide.md
The user guide did not correctly specify how to create a Namespaced install (referring still to deprecated `global.limitedScope`).
> Update instructions for global.scope=Namespaced

- docs/development.md
- docs/userguide.md
For download part, currently, we have `kubefed2`. I don't want to make it here because it is obsolete. I just use new command name for download part for future release download.
Fixes #654
> doc installation for kubefedctl

- pkg/controller/sync/controller.go
- pkg/controller/sync/dispatch/checkunmanaged.go
- pkg/controller/sync/dispatch/unmanaged.go
Since a federated resource may be deleted before all the resources it manages appear in the informer cache, it is necessary to manually check each member cluster that does not have a cached resource before removing the finalizer.
This PR addresses a [TODO item in the old deletion helper](https://github.com/kubernetes-sigs/federation-v2/blob/v0.0.8/pkg/controller/util/deletionhelper/deletion_helper.go#L125). 
This is a repost of #784 that I unintentionally closed.
> Ensure finalizer is not removed if uncached managed resources exist

- CHANGELOG.md
I realised that I did not update the `CHANGELOG` per PR, that I was supposed to do and @marun did the job of reflecting the updates in the release notes in the last 3 releases he made. Hearty thanks @marun for doing that.
Also not sure if its worth updating the details now; but raising this anyways to keep the `CHANGELOG` in sync with the release notes.
> Update changelog to reflact federate resource changes

- pkg/controller/federatedcluster/clusterclient.go
- pkg/controller/federatedcluster/controller.go
This is one of the step which would improve reliability of cluster health checks. This was missed previously.
> Add timeout to cluster clients used for cluster health checks

- charts/federation-v2/Chart.yaml
- docs/releasing.md
- scripts/build-release-artifacts.sh
- Add script to build release artifacts
- Remove documentation of artifact build (replaced by script)
- Remove appVersion from chart yaml to avoid having to maintain it
Partial fix for #813.   I tried automating the tag creation/push and it ended up being more trouble than it was worth.
> Add script to automate build of release artifacts

- CHANGELOG.md
- charts/federation-v2/templates/crds.yaml
- docs/userguide.md
- pkg/controller/sync/controller.go
- pkg/controller/sync/dispatch/checkunmanaged.go
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/dispatch/operation.go
- pkg/controller/sync/dispatch/unmanaged.go
- pkg/controller/sync/status/status.go
- pkg/controller/sync/version/manager.go
- pkg/controller/util/constants.go
- pkg/kubefedctl/enable/util.go
- pkg/kubefedctl/enable/validation.go
- test/common/crudtester.go
This PR ensures that propagation status is written for federated resources.   The PR looks large but the bulk of it is actually generated crd yaml.
TODO
Fixes #740
Fixes #588
> Write propagation status to reconciled federated resources

- Makefile
This should fix travis `master` builds in order to successfully push the `canary` tag.
> Update Makefile to use TRAVIS_BRANCH env var

- CHANGELOG.md
- pkg/kubefedctl/federate/federate.go
- pkg/kubefedctl/federate/util.go
- test/e2e/federate.go
- Federates resources given in input yaml (emits yaml output).
- Takes input from `stdin` if `-` is specified for file name.
> Federate resources from input yaml

- CHANGELOG.md
- charts/federation-v2/templates/crds.yaml
- docs/userguide.md
- example/sample1/federatedclusterrole.yaml
- example/sample1/federatedclusterrolebinding.yaml
- example/sample1/federatedconfigmap.yaml
- example/sample1/federateddeployment.yaml
- example/sample1/federatedingress.yaml
- example/sample1/federatedjob.yaml
- example/sample1/federatednamespace.yaml
- example/sample1/federatedsecret.yaml
- example/sample1/federatedservice.yaml
- example/sample1/federatedserviceaccount.yaml
- pkg/controller/sync/placement.go
- pkg/controller/sync/placement_test.go
- pkg/controller/util/constants.go
- pkg/controller/util/placement.go
- pkg/kubefedctl/enable/validation.go
This ensures that the addition of fields to cluster references will be backwards compatible.
Fixes #688
> Switch cluster references in placement from strings to objects

- Makefile
This prevents running `docker login` using the quay credentials if we don't have any travis secure environment vars set e.g. running travis in forked repos.
> Run E2E with travis in forked repos

- pkg/kubefedctl/unjoin.go
`unjoin`: when resources does not exists, ignore it and delete other resources continuely until try my best. This is almost `--force` by default.
Fixes #745
> idempotent unjoin

- charts/kubefed/README.md
- charts/kubefed/charts/controllermanager/templates/crds.yaml
- charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
- charts/kubefed/values.yaml
- cmd/controller-manager/app/controller-manager.go
- cmd/controller-manager/app/leaderelection/leaderelection.go
- cmd/controller-manager/app/options/options.go
- config/kubefedconfig.yaml
- docs/userguide.md
- example/config/kubefedconfig.yaml
- pkg/apis/core/v1alpha1/kubefedconfig_types.go
- pkg/controller/kubefedcluster/controller.go
- pkg/controller/kubefedcluster/controller_test.go
- pkg/controller/util/cluster_util.go
- pkg/controller/util/controllerconfig.go
- test/e2e/framework/controller.go
Partial fix for #879 .
**NOTE:** Due to the K8s API conventions doc being ambiguous over the use of pointers for optional fields, I have kept optional fields without a built-in `nil` value as non-pointers for now. This is subject to change pending a more formal API review.
> Align FederationConfig API with K8s API conventions

- CONTRIBUTING.md
- README.md
- charts/kubefed/README.md
- docs/concepts.md
- docs/development.md
- docs/environments/gke.md
- docs/environments/icp.md
- docs/environments/kind.md
- docs/environments/minikube.md
- docs/ingress-service-dns-with-coredns.md
- docs/ingressdns-with-externaldns.md
- docs/releasing.md
- docs/servicedns-with-externaldns.md
- docs/userguide.md
The Federation project has been renamed KubeFed. This change renames all
appropriate occurrences in the docs.
The format is KubeFed, in UpperCamel, per agreement on 2019-05-15
Federation WG meeting. The longform is Kubernetes Cluster Federation,
per clarification on PR #912. The kubefed2 CLI tool was renamed
kubefedctl, per the 0.0.10 changelog.
Specifically searched for:
* Kubefed (case sensitive)
* Should not occur except in immutable CHANGELOG.
* kubefed (case sensitive)
* Should only occur when in code, URLs, Markdown links, similar.
* kubefed (case insensitive)
* Reviewed for any unexpected capitalizations, found none.
* v2 (case insensitive)
* Should not occur in relation to Federation
* Federation (case sensitive)
* Should only occur in immutable CHANGELOG, in reference to history …
> Rename Federation V2 to KubeFed in all docs

- CONTRIBUTING.md
- README.md
Rewrite the README intro and fix a couple other places where federation is likely better written as Kubefed
> Rewrite README intro

- charts/index.yaml
- charts/kubefed/README.md
- scripts/build-release-artifacts.sh
The vanity url doesn't work for asset download links.
This commit also fixes the use of the vanity url in the asset build script and updates the chart readme to refer to the `kubefed` chart.
> Fix broken chart index link for v0.1.0-rc1

- pkg/apis/core/common/constants.go
- pkg/apis/core/v1alpha1/clusterpropagatedversion_types.go
- pkg/apis/core/v1alpha1/propagatedversion_types.go
- pkg/kubefedctl/enable/directive.go
- test/e2e/crd.go
`comparisonField` is a legacy field that was removed in favor of dynamically determining which metadata field to use in propagation
versioning.  This commit removes all remaining traces of the field.
> Remove all trace of comparisonfield

- pkg/controller/kubefedcluster/controller.go
Fixes: https://github.com/kubernetes-sigs/kubefed/issues/878
/cc @font @marun
> Retry adding cluster client if one doesn't exist during cluster healthcheck

- docs/userguide.md
- scripts/create-clusters.sh
- scripts/fix-joined-kind-clusters.sh
Found some tiny problems when deploy with MacOS.
1. `sed` in place is not compatible with MacOS.
2. create cluster with `kind` name error. should prefix with `kind` as the context showed.
3. Fix cluster.registry address, change from `localhost` to `container ip address`.
Signed-off-by: Aoxn <yaoyao.aoxn@hotmail.com>
> Make installation compatible with macos under docker 18 with kind.

- docs/environments/kind.md
- docs/userguide.md
- scripts/create-clusters.sh
- scripts/download-binaries.sh
- scripts/fix-joined-kind-clusters.sh
- scripts/pre-commit.sh
This is a follow-up to #706 to fix compatibility with the current state of the API and ensure the kind fixup script conforms to the bash conventions used by other scripts.
This PR also:
- ensures that the `create-servers.sh` script does not attempt to configure a container registry if `CONFIGURE_CONTAINER_REGISTRY` is not set to ensure compatibility with a MacOS deployment environment that hosts the docker daemon in a VM.
- fixes the download of `golangci-lint` on macos
- adds support to the kind fixup script for e2e testing on macos with in-memory controllers
> Fix macos deployment compatibility

- pkg/apis/core/v1beta1/validation/validation.go
- pkg/apis/core/v1beta1/validation/validation_test.go
PR #973 naively attempted to resolve the conflict created by merging PRs #966 and #944 by dereferencing pointers where necessary to satisfy the linter.  This change goes further and adds validation checks for nil values to ensure that pointer values are validated to be present without risking null pointer exceptions.
Please prioritize merging this PR to minimize the potential for other developers encountering the bugs introduced by the referenced PRs.
> Fix KubeFedConfig validation of pointer fields

- charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
- charts/kubefed/charts/controllermanager/templates/webhook.yaml
- pkg/apis/core/v1beta1/validation/validation.go
- pkg/controller/webhook/federatedtypeconfig/webhook.go
- pkg/controller/webhook/kubefedcluster/webhook.go
- pkg/controller/webhook/kubefedconfig/webhook.go
- pkg/controller/webhook/util.go
- pkg/webhook/webhook.go
This PR renames the `admission.core.kubefed.k8s.io` API group to `validation.core.kubefed.k8s.io`, and refactors the validating admission webhook interface methods in preparation for enabling mutating webhooks. It also adds more logs for debug purposes.
> Rename and refactor validation admission webhooks

- charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
- charts/kubefed/charts/controllermanager/templates/webhook.yaml
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/webhook/kubefedconfig/webhook.go
- pkg/controller/webhook/util.go
~~**NOTE:** This PR is not reviewable until #977 merges.~~
This adds the initial support for a mutating webhook for `KubeFedConfig`. The subsequent work after this PR will involve adding the defaulting logic for `KubeFedConfig`.
> Add mutating webhook support for KubeFedConfig

- docs/environments/icp.md
IBM Private Cloud default PSP prevents running pods as `root`. This PR adds explanation how to configure ICP's PSP.
> Add explanation, how to configure PSP for the kubefed namespace on ICP

- OWNERS
@xunpan has proven a solid contributor to KubeFed since he started last year and I believe that he has demonstrated the capability and commitment to the long-term success of the project that justify his elevation to the status of `approver`.
> Add Xun Pan as an approver

- scripts/deploy-kubefed.sh
fix issues similar to #990. Use `-` instead of `:-` in variable expansion: when `DOCKER_PUSH` is set empty, the script should not set `y` but keep it as is.
> when DOCKER_PUSH= is set, the script should skip docker push

- docs/userguide.md
`spec.placement.clusterNames` -> `spec.placement.clusters`
> Fix typo in user-guide

- charts/kubefed/charts/controllermanager/templates/deployments.yaml
- images/kubefed/Dockerfile
- the hyperfed user is create with UID 1001
- the controller and webhook pods are run with a security context setting `runAsUser: 1001` so that kubernetes knows it's not running as a root user (supporting restricted pod security policies)
- also create the `hyperfed` user in a named group which seems to be required for `chown` to apply correctly
- also execute `chown` after copying binaries to hyperfed path as the binaries were ending up owned by `root` in my testing
> configure images with a UID and set SC in deployments

- docs/userguide.md
The release binaries have a new naming syntax compared with the old release.
Currently, the version specified in the path differs from the version specified in the file name, it may be something we want to look at/adjust going forward so we don't need to have the `v${VERSION}` in the path:
> Update install instructions for kubefedctl

- docs/userguide.md
Fix typo in user guide,
Its -> It's
Thanks.
> Fix typo in user guide

- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/resource.go
- Always adapt resources for `FederatedNamespace` in host cluster. Fix for #1002
> Always adopt resources for FederatedNamespace in host cluster

- CHANGELOG.md
- docs/userguide.md
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/dispatch/retain.go
- pkg/controller/sync/resource.go
- pkg/controller/sync/status/status.go
Now that [overriding via jsonpatch is supported](https://github.com/kubernetes-sigs/kubefed/pull/991), it is possible to restrict modification of the `annotations` and `finalizers` fields to overrides. Modifications to these collection fields can be made using the `add` or `remove` jsonpatch operations to ensure that a given item exists (or does not exist) with less chance of conflicting with local controllers.
```yaml
kind: FederatedDeployment
...
spec:
...
overrides:
- clusterName: cluster1
clusterOverrides:
- path: "/metadata/annotations"
op: "add"
value:
foo: bar
- path: "/metadata/annotations/foo"
op: "remove"
```
To support this change, it was necessary to move the application of overrides from before retention of local values to after so  that overrides would be applied to the …
> Always retain metadata.finalizers and metadata.annotations

- cmd/controller-manager/app/controller-manager.go
Fix typo in the usage message of controller manager. The word `which` here means `a bunch of controllers`, so we should not use the third person singular.
watches -> watch
does -> do
Thanks.
> Fix typo in the usage message of controller manager

- docs/releasing.md
- scripts/build-release-artifacts.sh
Update the release doc to verify `helm` is installed prior to executing the release script. Also updates the release script for:
- new Makefile build targets after merging of #1039
- adds a check for `helm` being installed.
> Update release script and doc

- docs/environments/gke.md
In GKE, the kubefed-controller fails to start up because it cannot create
new kubefed objects. This is because the API server attempts to
communicate to the Pod directly rather than going through the service.
This is intended behaviour when the API server runs with the
`--enable-aggregator-routing=true`.
An additional firewall rule within the VPC network firewall rules must
be added. The GKE installation guide has been extended to inform the
users of this issue.
Resolves #1024
> Adding documentation to solve the kubefed-admission-webhook timeout

- CHANGELOG.md
- docs/userguide.md
- pkg/controller/sync/controller.go
- pkg/controller/sync/resource.go
- pkg/controller/sync/status/status.go
- scripts/pre-commit.sh
- test/common/crudtester.go
- test/e2e/crud.go
- test/e2e/framework/test_context.go
Previously a namespaced resource whose containing namespace was not federated (i.e. did not contain a `FederatedNamespace` resource) would report a healthy propagation status.  This has been changed to reporting unhealthy propagation status with reason `NamespaceNotFederated`.
Fixes #951
> Report NamespaceNotFederated in propagation status

- charts/kubefed/charts/controllermanager/templates/crds.yaml
- pkg/apis/core/v1beta1/kubefedcluster_types.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/controller/kubefedcluster/clusterclient.go
- pkg/controller/kubefedcluster/controller.go
- pkg/controller/kubefedcluster/controller_test.go
- pkg/controller/servicedns/controller.go
- test/common/validation.go
- test/e2e/servicedns.go
This updates the optional fields in `KubeFedClusterStatus` to make them pointers. It also makes `KubeFedClusterSpec` required as it was inadvertently changed previously.
Additionally, a couple more cluster conditions are added to the shared `ValidKubeFedCluster` test object (to complete all 4 possible conditions) as a result of changes for this PR.
> Update KubeFedCluster API optional fields

- charts/kubefed/charts/controllermanager/templates/crds.yaml
- pkg/apis/core/v1beta1/kubefedcluster_types.go
- pkg/apis/core/v1beta1/validation/validation.go
- pkg/apis/core/v1beta1/validation/validation_test.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/controller/util/cluster_util.go
- pkg/kubefedctl/join.go
Implements an optional field in v1beta1/KubeFedCluster to specify which TLS checks to ignore. Disabling TLS checks is implemented by setting tls.Config.InsecureSkipVerify and providing a function closure implementing tls.Config.VerifyPeerCertificate (to selectively ignore SubjectName or ValidityPeriod).
Modifies kubefedctl join to preserve the kubeconfig cluster setting of InsecureSkipTLSVerify by setting the new field in v1beta1/KubeFedCluster.
Related issue:
https://github.com/kubernetes-sigs/kubefed/issues/1029
> Kubefedcluster: support ignore tls

- CHANGELOG.md
- pkg/client/generic/genericclient.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/dispatch/checkunmanaged.go
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/dispatch/operation.go
- pkg/controller/sync/dispatch/unmanaged.go
- pkg/controller/sync/resource.go
- pkg/controller/util/federated_informer.go
- pkg/controller/util/overrides.go
- pkg/controller/util/podanalyzer/pod_helper.go
- pkg/controller/util/podanalyzer/pod_helper_test.go
- pkg/schedulingtypes/replicascheduler.go
- scripts/download-binaries.sh
Previously the sync controller used `ResourceClient` to make changes to member clusters. This meant that the API endpoint configuration for a target type was always sourced from an FTC.
This PR updates the sync controller to use `GenericClient` so that API endpoint configuration for create and update calls can be provided on a per-call basis. If `apiVersion` is set via template or override for a given federated resource, that value will supersede the configuration sourced from an FTC. This is intended to allow a given federated type to manage more than one version across member clusters. For example, federated resource `foo` could manage a resource in cluster1 at v1, and a resource in cluster2 at v2. It would still be necessary for all clusters to support the version defined in the FTC …
> Support varying the apiVersion of target resources

- scripts/pre-commit.sh
This is in response to recent CI failures due to the race detection test run failing to complete in the default 600s.
> Extend race detection timeout to 900s from default 600s

- pkg/kubefedctl/options/options.go
This will hopefully make it easier for a user to diagnose targeting kubefedctl at a namespace that is missing a KubeFed control plane.
> Improve kubefedctl error message when KubeFedConfig not found

- CHANGELOG.md
- cmd/controller-manager/app/controller-manager.go
- pkg/apis/core/v1beta1/validation/validation.go
- pkg/apis/core/v1beta1/validation/validation_test.go
- pkg/controller/webhook/federatedtypeconfig/webhook.go
- pkg/controller/webhook/kubefedcluster/webhook.go
- pkg/controller/webhook/kubefedconfig/webhook.go
- pkg/controller/webhook/util.go
This PR makes the KubeFedConfig `spec.scope` field immutable.
Fixes #1058 
```release-note
```
> Make KubeFedConfig scope immutable

- pkg/apis/core/v1beta1/federatedtypeconfig_types.go
- pkg/controller/status/controller.go
Set default value for statusType
When statusType is not set, return targetType.
Fixes https://github.com/kubernetes-sigs/kubefed/issues/1069
```release-note
```
> Fix panic when statusCollectoin is enabled

- pkg/schedulingtypes/plugin.go
ReplicaSchedulingPreference's plugin doesn't updates FederatedDeployment with latest overrides of replica count.
Fixes #1087 
> 1087. Replica count of federated deployment is not updated by RSP plugin

- Makefile
In Makefile, container tag miss to handle darwin OS
> Add image build for darwin

- Makefile
Reverts kubernetes-sigs/kubefed#1094
There's a reason we don't support building a container with a darwin binary. Containers are linux-only, so a kubefed image with a darwin binary is by definition a broken container.
cc: @gyliu513 @xunpan @hougangliu
> Revert "Add image build for darwin"

- scripts/pre-commit.sh
- test/e2e/ftccontroller.go
`kind` v0.4.0 now supports kube v1.15.0 so this updates the CI script to deploy and test against kube v1.15.0.
Fixes #1079 
```release-note
```
> Update CI to test against kube v1.15.0

- pkg/controller/kubefedcluster/controller.go
- pkg/controller/util/federated_informer.go
This PR addresses label update handling on KubeFedCluster resources.  Adding/removing labels was not triggering federated resource sync.
> controller: process label updates to kubefedcluster resources

- CHANGELOG.md
- charts/kubefed/templates/crds.yaml
- pkg/controller/sync/resource.go
- pkg/kubefedctl/enable/validation.go
- test/e2e/framework/framework.go
A missing spec field in a federated resource is a potential indication of a malformed resource. For existing resources, a check has been added for a missing spec field before attempting to compute a hash of overrides to prevent a nil pointer exception.
Fixes #1079
> Require the spec field in generated federated types

- CHANGELOG.md
- pkg/kubefedctl/federate/federate.go
- pkg/kubefedctl/federate/util.go
- test/e2e/federate.go
Previously `kubefedctl federate` removed a subset of metadata fields from the resource targeted for conversion to a federated resource. It wasn't removing `metadata.annotations` or `metadata.finalizers` despite those fields not being supported for propagation. This change ensures that all metadata fields are removed except labels to ensure that fields set by the local cluster and its controllers are not included in the template of the new federated resource.
> Remove all metadata fields but labels from targets of kf federate

- scripts/deploy-kubefed.sh
This PR ensures that the necessary binaries used by the script are installed before proceeding to perform any deployment actions.
```release-note
```
> Add fatal check to deploy script for binary dependencies being installed

- test/e2e/schedulermanager.go
- test/e2e/scheduling.go
this fix divides scheduling of RSP and scheduler managing test apart.
it helps scheduler manager test in independent test namespace to avoid
issues that existing FTC in kubefed namespace has finalizer because
deployed kubefed control plane set it for other tests.
Fixes #1084
> fix scheduler manager test case

- CHANGELOG.md
- pkg/kubefedctl/join.go
- pkg/kubefedctl/options/options.go
- pkg/kubefedctl/orphaning/orphaning.go
- pkg/kubefedctl/unjoin.go
- pkg/kubefedctl/util/util.go
For any invocation of `kubefedctl` that does not specify a value for `--host-cluster-context`, the current config context will be
used. However, other usage of the `HostClusterContext` variable requires explicitly looking up the name of the current context to avoid using an empty string.
#1065 fixed the `join` command to lookup the current context. This change ensures the same lookup is performed for all `kubefedctl` commands.
> kubefedctl: Set host cluster context to current context if empty

- pkg/kubefedctl/join.go
Previously, `kubefedctl join` assumed internally that the kubefed namespace in the joining cluster should be the same as the kubefed namespace in the host cluster. This refactor allows the kubefed system namespace in the member cluster to vary in support of simulated scale testing. This is not a user-visible change and is not intended for external consumption.
>  Refactor `kubefedctl join` to enable reuse for simulated scale testing

- CHANGELOG.md
- pkg/controller/sync/version/manager.go
The existing check for unchanged propagated version status was still resulting in an unnecessary API update.
> Skip writing propagated version to the API when unchanged

- CHANGELOG.md
- charts/kubefed/templates/crds.yaml
- docs/userguide.md
- pkg/controller/sync/controller.go
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/status/status.go
- pkg/controller/sync/status/status_test.go
- pkg/controller/sync/version/manager.go
- pkg/controller/util/constants.go
- pkg/kubefedctl/enable/validation.go
Each status update to a federated resource results in a subsequent reconcile. Previously this was creating an endless cycle of reconciliation even when there were no propagation changes since the `lastProbeTime` timestamp was always changed even if nothing else did. This induced unnecessary overhead in the controller manager, kube apiserver, and etcd.
Kubernetes saw a similar problem with `lastProbeTime` on pods: https://github.com/kubernetes/kubernetes/issues/14393
This PR limits propagation status updates to when the status has actually changed - either due to a propagation error or changes being propagated to member clusters. This suggested replacing `lastProbeTime` with `lastUpdateTime`.
> Minimize updates to propagation status

- pkg/kubefedctl/enable/enable.go
- pkg/kubefedctl/federate/federate.go
- test/e2e/crd.go
- test/e2e/ftccontroller.go
- test/e2e/schedulermanager.go
This PR propagates the dry run flag to the `enable type` functionality
fixes #1102
> kubefedctl federate: ensure that --dry-run avoids mutating api state

- pkg/kubefedctl/federate/util.go
Certain secrets and service accounts in Openshift have a ":" in their names and if we try to federate these resources in a given namespace, we get a validation error: 
```F0812 16:15:45.724853    6232 federate.go:150] Error: Error creating federated resource "test-namespace/system:deployers": FederatedRoleBinding.types.kubefed.io "system:deployers" is invalid: metadata.name: Invalid value: "system:deployers": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```
This PR skips federating resources whose names don't conform to the DNS-1123 …
> Fix BZ 1740052 - Federation of SAs and Secrets that have a : in them doesn't work because of CRD expression limitation

- pkg/webhook/webhook.go
This adds version info to the KubeFed admission webhook server similar to the `controller-manager` and `kubefedctl`
> Add version info to KubeFed admission webhook

- CHANGELOG.md
- pkg/kubefedctl/federate/federate.go
The `--enable-type` long option can be accidentally typed with only 1 `-` as in `-enable-type` resulting in the following error:
```bash
$ kubefedctl federate secret kubefed -enable-type
F0809 15:24:48.160303   17400 federate.go:150] Error: Error retrieving target Secret "able-type/kubefed": secrets "kubefed" not found
```
The error occurs because combined shorthand options as in `-en` are valid. If a shorthand option takes an argument, as in `-n`, it must be the last argument, so it interprets the rest of the command `able-type` as the namespace argument. This can be confusing and is only a special case because `e` and `n` are both shorthand flags while their combined use spells out the long form of an option.
This fixes that by changing the …
> Change shorthand --enable-type flag to avoid typo

- .travis.yml
- Makefile
- pkg/apis/core/v1beta1/validation/validation_test.go
This update includes changes to handle a backported CVE fix for CVE-2019-14809 [1] that was introduced in go 1.12.8 [2]. That fix results in the `url.Parse` API making sure port is only decimals, so the validation code will now catch the error earlier instead of later in the `Atoi` conversion.
[1] https://github.com/golang/go/commit/3226f2d492963d361af9dfc6714ef141ba606713
[2] https://github.com/golang/go/issues/33633
> Update to use go 1.12.9

- scripts/build-release.sh
- scripts/create-gh-release.sh
This PR adds the following updates to the release automation scripts:
- Increases the timeout to wait for Travis CI job to begin as I've seen it queued for 10-15 minutes before actually starting.
- Makes `build-release.sh` script idempotent in the event a timeout does occur or if the user accidentally cancels the script.
- Adds check to `create-gh-release.sh` to make sure assets file exists first before proceeding.
> Update kubefed release automation scripts

- pkg/kubefedctl/join.go
This avoids the potential for accidentally joining a new cluster with the same name as an old cluster, effectively disconnecting the old cluster from the control plane.
> kubefedctl: Default --error-on-existing=true for join

- pkg/apis/core/v1beta1/validation/validation.go
- pkg/apis/core/v1beta1/validation/validation_test.go
This relaxes the KubeFedCluster APIEndpoint validation to more closely match what k8s does. While this will avoid catching some errors such as invalid IP addresses (e.g. multiple dots) and some DNS 1123 non-compliant URLs, it will be more accepting to some examples as captured in #1148.
Fixes #1148
> Relax KubeFedCluster APIEndpoint validation

- scripts/create-clusters.sh
Given that there is often a lag between a kube release and when official kind images become available for that release, it may be necessary for developers to build their own kind node images for testing. This change allows providing a custom image name via the `KIND_IMAGE` env var to `scripts/create-clusters.sh` script.
> Allow setting custom kind image to create-servers.sh via KIND_IMAGE

- pkg/kubefedctl/join.go
- test/e2e/scale.go
When using kubefed as a library, returning the created `kubefedcluster` is very useful to be able to set references, ownership, etc after successful creation.
> Return created kubefedcluster from JoinCluster

- docs/userguide.md
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/status/status.go
- pkg/controller/util/managedlabel.go
when a resource object in member cluster has managed label false, it should not be managed by the federated resource
This addresses partial of 1003
Fixes #
> check managed=false in member cluster

- charts/kubefed/charts/controllermanager/templates/aggregate_clusterroles.yaml
- pkg/controller/util/federated_informer.go
**What this PR does / why we need it**: The kubefed cluster roles are not aggregated to default kubernetes cluster roles, as you could expect. That is a common practice to aggregate the rules of custom resources to the existing kubernetes cluster roles such as view, edit, admin. That'll keep the consistency and purpose of these cluster roles.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: fixes #1170 
Fixes #
> charts: create aggregated cluster roles to the standard kubernetes roles

- cmd/controller-manager/app/controller-manager.go
- docs/userguide.md
Adds pprof profiling support and accompanying documentation. 
The data provided by pprof is useful to track down any potential performance bottlenecks as well to figure out areas of improvement. Being able to get a stacktrace of kubefed is also very useful.
Fixes #
> feat: Add pprof profiling support

- charts/kubefed/charts/controllermanager/templates/deployments.yaml
- charts/kubefed/charts/controllermanager/templates/service.yaml
- cmd/controller-manager/app/controller-manager.go
- go.mod
- go.sum
This PR exposes default controller metrics and makes both `healthz-addr` and `metrics-addr` configurable via flags.
```
rest_client_request_latency_seconds_bucket{url="https://10.0.0.1:443/%7Bprefix%7D",verb="GET",le="0.001"} 33
rest_client_request_latency_seconds_bucket{url="https://10.0.0.1:443/%7Bprefix%7D",verb="GET",le="0.002"} 156
rest_client_request_latency_seconds_bucket{url="https://10.0.0.1:443/%7Bprefix%7D",verb="GET",le="0.004"} 606
rest_client_request_latency_seconds_bucket{url="https://10.0.0.1:443/%7Bprefix%7D",verb="GET",le="0.008"} 1779
rest_client_request_latency_seconds_bucket{url="https://10.0.0.1:443/%7Bprefix%7D",verb="GET",le="0.016"} 2057
rest_client_request_latency_seconds_bucket{url="https://10.0.0.1:443/%7Bprefix%7D",verb=" …
```
> chore: serve controller default metrics

- pkg/controller/status/controller.go
- pkg/controller/sync/accessor.go
- pkg/controller/util/federated_informer.go
- pkg/controller/util/resourceinformer.go
- pkg/schedulingtypes/plugin.go
Rebases #1146 with master to bring it up to date. We've used that PR successfully to track down a couple of problems and didn't found any issues while using it.
Close #1146 
Fixes #1083
> (Updated) #1083: use unstructured runtime.Object for more detailed reflector logging

- docs/releasing.md
- scripts/build-release-artifacts.sh
- scripts/build-release.sh
- scripts/create-gh-release.sh
- scripts/util.sh
=**What this PR does / why we need it**:
Some tweaks to the release scripts to:
- Support alpha, beta, rc version suffixes
- Fix up git tag check
- Fix up check for image available from quay.io
Used in latest release, v0.2.0-alpha.1
> Release script improvements

- scripts/download-binaries.sh
The current version installed in the script (2.14.0) produces the following error when executing `helm init`:  **_Error: error installing: the server could not find the requested resource_**. This is due to an incompatibility with clusters with versions 1.16.0+, found on https://github.com/helm/helm/issues/6374.
To fix this, the Helm version is bumped to `2.16.3`.
> Bump Helm version to 2.16.3 in download-binaries script

- charts/kubefed/README.md
Helm search and install needs the devel flag, as currently the latest version of the chart is still a development release. However, this is not included in the documentation. As such, following the documentation will not lead to the desired effect.
Fixes #1203
> docs: add missing devel flag to helm commands (#1203)

- cmd/controller-manager/app/controller-manager.go
- docs/keps/20200302-kubefed-metrics.md
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/ingressdns/controller.go
- pkg/controller/kubefedcluster/clusterclient.go
- pkg/controller/kubefedcluster/controller.go
- pkg/controller/schedulingmanager/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/controller/servicedns/controller.go
- pkg/controller/status/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/dispatch/unmanaged.go
- pkg/controller/util/federated_informer.go
- pkg/kubefedctl/join.go
- pkg/kubefedctl/unjoin.go
- pkg/metrics/metrics.go
It adds kubefed custom metrics to the list of metrics exposed and serve by https://github.com/kubernetes-sigs/kubefed/pull/1193. It is a follow-up PR that allows to have a better view of the duration of some of the complex kubefed operations. 
Fixes #
related to: https://github.com/kubernetes-sigs/kubefed/issues/1194
I created a home made grafana dashboard to testthese metrics:
> feat: add custom kubefed metrics

- docs/userguide.md
- pkg/kubefedctl/enable/schema.go
`kubefedctl enable crd` command was throwing a panic as reported in https://github.com/kubernetes-sigs/kubefed/issues/1206. It is related to what @marun  did here https://github.com/kubernetes-sigs/kubefed/pull/470. I might need a bit more of context to address the TODO comment.
Fixes #
https://github.com/kubernetes-sigs/kubefed/issues/1206
```
kubefedctl enable crd
customresourcedefinition.apiextensions.k8s.io/federatedcustomresourcedefinitions.types.kubefed.io created
federatedtypeconfig.core.kubefed.io/customresourcedefinitions.apiextensions.k8s.io updated …
```
> fix: enable command for crd resources

- pkg/kubefedctl/federate/federate.go
- pkg/kubefedctl/federate/federate_test.go
The current code checks if the api resource is namespaced or not by a faulty condition,
`apiResource.Namespaced = targetResource.GetNamespace() == ""`
If the input kubernetes api-resource has a namespace, the above condition makes the federatedapi-resource not namespaced, due to which the namespaces are not populated in the federatedapi-resource.
Changing the above condition to
`apiResource.Namespaced = targetResource.GetNamespace() != ""`
makes the federated-api-resource as namespaced and sets the namespace as well.
Read more on [issue#1181](https://github.com/kubernetes-sigs/kubefed/issues/1181)
https://github.com/kubernetes-sigs/kubefed/issues/1181
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> FIX: namespaced condition for api resource

- go.sum
- pkg/controller/kubefedcluster/controller.go
- pkg/controller/kubefedcluster/controller_integration_test.go
- pkg/controller/kubefedcluster/controller_test.go
- pkg/controller/testdata/fixtures/crds.yaml
- scripts/download-binaries.sh
- scripts/pre-commit.sh
It is a continuation of https://github.com/kubernetes-sigs/kubefed/pull/1201 which has been stale for a long period. I cherry picked their changes and added some tests. 
This test also cover other functions of the kubefedcluster controller.
Fixes #
> test: add test to validate the controller actions to keep the cluster data

- pkg/apis/core/v1beta1/validation/validation_test.go
The following tests will fail when run with Go 1.14+:
```
[root@ecs-d8b6 kubefed]# go test ./pkg/apis/core/v1beta1/validation/ -run=TestValidateAPIEndpoint -v
=== RUN   TestValidateAPIEndpoint
TestValidateAPIEndpoint: validation_test.go:478: unexpected error: [apiEndpoint: Invalid value: "example.com:port80": parse "https://example.com:port80": invalid port ":port80" after host], expected: "apiEndpoint: Invalid value: \"exam"
TestValidateAPIEndpoint: validation_test.go:478: unexpected error: [apiEndpoint: Invalid value: "example.com:-80": parse "https://example.com:-80": invalid port ":-80" after host], expected: "apiEndpoint: Invalid value: \"example.com:-"
--- FAIL: TestValidateAPIEndpoint (0.00s)
```
The difference is whether the string included …
> Fix unit test failing with Go1.14+

- scripts/create-clusters.sh
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
The command 'kind get kubeconfig-path' has been deprecated in kind
v0.6.0 and removed in v0.7.0 so the cluster creation script doesn't
work with the latter version. To account for this fact and other
changes (such as kind now respecting `KUBECONFIG` and falling back to
the same defaults that `kubectl` uses), I reworked some parts of the
script.
pre-commit now uses the kind imave v1.17.5 for tests.
Note: This change makes the scripts fail to work with
kind version < v0.7.0.
Fixes #1220
> chore: make cluster creation work with kind v0.7.0

- pkg/controller/sync/accessor.go
I believe the function `isSystemNamespace` need a `namespace` but not a `name`. :)
Fixes #
> Fix event source namespace

- pkg/controller/sync/accessor.go
Reverts kubernetes-sigs/kubefed#1225
As mentioned by @zhouya0, when eventSource comes from a namespace resource, it might be :
```
Name: "test-namesapce"
Namespace: ""
```
Or in the case of a federated type namespace:
```
Name: "test-namespace/test-namespace"
Namespace: "test-namespace"
```
The function `isSystemNamespace` handles both scenarios:
```
func (a *resourceAccessor) isSystemNamespace(namespace string) bool {
// TODO(font): Need a configurable or discoverable list of namespaces
// to not propagate beyond just the default system namespaces e.g.
switch namespace {
case "kube-system", "kube-public", "default", a.fedNamespace:
return true
default:
return false
}
}
```
therefore we need to revert this change.
> Revert "Fix event source namespace"

- docs/ingress-service-dns-with-coredns.md
There are 4 issues updated in the document
1. switch from `minikube` to `kind`
2. add RBAC for clusterrole `external-dns`
3. add labels to make kubefed controller works
4. update link to metallb
Fixes #1217
> correct steps in ingress and service with coredns document

- docs/ingress-service-dns-with-coredns.md
use old tag of ingress nginx repo
https://github.com/kubernetes/ingress-nginx/tree/nginx-0.22.0/deploy
master branch：
https://github.com/kubernetes/ingress-nginx/tree/master/deploy
Fixes #
> [root@xxx-10-6-177-41 ~]# kubectl --context paco308 apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
> error: unable to read URL "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml", server reported 404 Not Found, status code=404
> 
Or you will get 404 error like above
> ingress-nginx master changed, so use nginx-0.32.0

- scripts/delete-clusters.sh
Kube config context didn't be removed after delete clusters, that would block creating cluster next time as same context is already exist. You can reproduce it by following command.
```
apiVersion: v1
clusters: null
contexts:
- context:
cluster: kind-cluster1
user: kind-cluster1
name: cluster1
- context:
cluster: kind-cluster2
user: kind-cluster2
name: cluster2
current-context: cluster1
kind: Config
preferences: {}
users: null
```
Fixes #
With this patch, we can get a clean config as follows:
```
apiVersion: v1
clusters: null
contexts: null
current-context: …
```
> cleanup legacy context after delete cluster

- docs/userguide.md
Adding a value to an array could be confusing for users, an example in the docs could alleviate the confusion.
Fixes #1224
> docs: adding documentation to add an array element using overrides

- charts/kubefed/values.yaml
Default [resource limits](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/values.yaml#L15-L17) in the chart is too low now, it's easy to cause OOM issues, like #1235. Enlarge kubefed controller resource limits would cover more cases.
```yaml
resources:
limits:
cpu: 100m
memory: 128Mi
```
Fixes #1235 
> increase resource limits for kubefed controller

- pkg/controller/status/controller.go
> Fix service status not working issue

- docs/userguide.md
While browsing I found that an example in the **Cluster Selector** part of the _userguide_ has a volatile mistake.
> Correct docs for a Cluster Selector case

- charts/kubefed/charts/controllermanager/templates/deployments.yaml
- charts/kubefed/values.yaml
Set default log level to `2` for the controller manager.
With this level, more useful logs would be printed and without much noise.
**Which issue(s) this PR fixes** :
Fixes #1246
> Set default log level for kubefed controller manager.

- charts/kubefed/charts/controllermanager/templates/deployments.yaml
- charts/kubefed/values.yaml
We should split the webhook properties from the manager properties.
Also we should expose the env properties for the chart as well.
Fixes #
Closes #1259 
> charts: split properties for webhook and manager

- scripts/deploy-kubefed.sh
The structure has been changed in
12b16661959272f01f1ae7b700ba2acbda43722e but the deploy script has
not, which led to the e2e cluster always loading the default image
quay.io/kubernetes-multicluster/kubefed:canary.
This commit changes the deploy script accordingly so that it passes in
the correct values again.
no issue
> fix: pass correct values to Helm release in deploy script

- Makefile
- docs/development.md
- scripts/deploy-kubefed.sh
This PR updates `deploy-kubefed.sh` script so it has better support for deploying locally on kind and enabling running deploy script multiple times.
This PR also includes a new `Makefile` target, `deploy.kind`, to run `deploy-kubefed.sh` easily against local kind clusters without having to push to a Docker registry.
Fixes #
> Improvements to deploy-kubefed.sh script

- docs/keps/20200619-federated-resource-status.md
It proposes a Kep to improve the visibility of the health of the federated resources using the current status field of the federated resources.
Nowadays users have to connect to the kubefed clusters to be aware if the federated
resources (deployments) are healthy or not across all the kubefed clusters.
Fixes #
> docs: add kep about the status of the federated resources

- Makefile
- charts/kubefed/Chart.yaml
- charts/kubefed/charts/controllermanager/templates/deployments.yaml
- charts/kubefed/requirements.yaml
- charts/kubefed/values.yaml
- scripts/deploy-kubefed.sh
Tidies up some deployment things from the helm3 chart migration, namely:
- Moves dependencies into `Chart.yaml` as recommended by Helm 3 chart guide
- Adds `forceRedeployment` option to chart to work around removal of `--recreate-pods` flag in upcoming helm 3 versions
- Adds `--wait` for deployments to finish
- Minor tidy up in `deploy-kubefed.sh` script
FYI @eumel8 @alejandroEsc
> Helm chart tidy up

- pkg/controller/webhook/federatedtypeconfig/webhook.go
- pkg/controller/webhook/kubefedcluster/webhook.go
- pkg/controller/webhook/kubefedconfig/webhook.go
- pkg/controller/webhook/util.go
Having these functions modify the AdmissionResponse passed in as
parameter makes it hard to reason about the code.
Fixes #1267 
> chore: webhook functions now return AdmissionResponse

- docs/userguide.md
Very minor cleanup of some repeated text
N/A
> docs[userguide]: clean up redundant text

- charts/kubefed/charts/controllermanager/templates/webhook.yaml
- charts/kubefed/values.yaml
Certain clusters may have other versions of cert-manager installed. This PR allows you to deploy certs based on the api group and version installed. 
Fixes #
> chart: cert-manager resources, allow these apiVersions be configurable

- charts/kubefed/charts/controllermanager/templates/webhook.yaml
- charts/kubefed/values.yaml
Changes cert-manager resources to those whose group/version are "cert-manager.io/v1"
This was tested on a kind cluster with the latest version of cert-manager. 
Fixes #
> chore: use cert-mananager.io/v1 group/version

- charts/index.yaml
Removing the old federation-v2 from the Helm repo as this chart just leads to confusion on user's side and it's deprecated,
anyway.
no issue
> chore: remove deprecated chart from repo

- docs/userguide.md
- pkg/kubefedctl/enable/util.go
When a resource type such as `pods` is `services` is passed to
`kubefedctl enable` and there's a match for this name in the `core`
group as well as another group, there was no way to tell `kubefedctl`
that the `core` resource should be enabled.
Now, whenever an API resource from the `core` group matches the
desired type to be enabled, this resource type is preferred.
Fixes #1078 
Here's the steps to test this:
-  `kind create cluster`
- `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.18.0/serving-crds.yaml`
- `make …
> fix: prefer core resources when enabling a type

- scripts/create-clusters.sh
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
Upgrades to use Kind v0.9.0 and Kubernetes v1.19.1. This is to unblock #1301 as a separate PR.
Fixes #
I haven't tested this on a Mac so help there would be appreciated. @makkes I see you've previously touched these files and I'm pretty sure you're a Mac user - would you be able to help our here? This can be tested with
```shell
$ DOWNLOAD_BINARIES=y bash -x ./scripts/pre-commit.sh`
```
and cleaned up with
```shell
DELETE_INSECURE_REGISTRY=y ./scripts/delete-clusters.sh
```
> chore: Use Kubernetes v1.19.1 and kind v0.9.0 for testing

- Makefile
- docs/environments/kind.md
- scripts/create-clusters.sh
- scripts/delete-clusters.sh
- scripts/deploy-kubefed.sh
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
Removes the need for the insecure registry deployment and configuration from running e2e tests locally with kind.
Fixes #496.
> chore: Remove need for insecure registry

- scripts/deploy-kubefed.sh
After #1306 has been merged, `make deploy.kind` broke because it doesn't provide the`KIND_CLUSTER_NAME` variable. An empty default provided to `kind`'s `--name` parameter doesn't make much sense because `kind` will simply error out in that case so using a default of `kind` for the name is the solution that should work most of the time, especially when following the quick start guide in the README.md.
Fixes #
> fix: `make deploy.kind` didn't work, anymore.

- cmd/controller-manager/app/controller-manager.go
- cmd/hyperfed/main.go
- pkg/kubefedctl/kubefedctl.go
Signed-off-by: Hector Fernandez <hfernandez@mesosphere.com>
The verbosity level was not initialized to klog anymore, so the level of verbosity was the default one instead of the specified in the flags.
Fixes #1314 
> fix: klog verbosity detection

- docs/environments/kind.md
- scripts/create-clusters.sh
- scripts/pre-commit.sh
The script should work based on documents.
1. I add default TAG for the node image to make it work by default.
2. I add 2 environment variables documented in kind doc
Fixes #1322
> make create-clusters.sh work based on kind document

- scripts/deploy-kubefed.sh
- scripts/sync-up-helm-chart.sh
* deploy-kubefed.sh: new envvar `NO_JOIN_HOST_CLUSTER`. When set to a
non-empty value prevents the script from joining the host cluster to
itself. Default behaviour doesn't change.
* sync-up-helm-charts.sh: reduced verbosity of the script by letting
etcd and kube-apiserver log into files instead of stdout/stderr.
This should make it much easier to follow the steps the scripts is
exercising. Also improved the two messages printed when waiting for
etcd and kube-apiserver to get ready.
n/a
No behaviour has been changed with respect to what the scripts do but …
> chore: improve some of the deployment and build scripts

- pkg/controller/sync/dispatch/retain.go
- pkg/controller/sync/dispatch/retain_test.go
Signed-off-by: Bruce Ma <brucema19901024@gmail.com>
For services which type==LoadBalancer and externalTrafficPolicy==Local, their field `spec.healthCheckNodePort` will be allocated by APIServer, and after that it should be unchangeable, so we should retain this field during update, just like `spec.clusterIP` and `nodePort` in ports.
Here we don't need to check whether the desired service need `healthCheckNodePort` but just pass it on, because if the passed `healthCheckNodePort` is not needed any more, it will be recycled by APIServer.
Codes in kubernetes about the validation on `spec.healthCheckNodePort`, [https://github.com/kubernetes/kubernetes/blob/68108c70e29a74bb455ab63adeb5725a37e94e4f/pkg/registry/core/serv …
> retain healthCheckNodePort for service when updating

- pkg/kubefedctl/enable/util.go
When execute command `kubefedctl enable clusterrole`，if some apiservices have error（like `v1alpha1.wardle.example.com`）,  command will fail. We could ignore the error if apiserver has the resource, just like `kubectl api-resource` return data and error.
```
[root@tpaas ~]# kubectl get apiservice
NAME                                   SERVICE      AVAILABLE                  AGE
v1alpha1.scheduling.kubefed.io         Local        True                       2d3h
v1alpha1.wardle.example.com            wardle/api   False (MissingEndpoints)   67m
v1beta1.admissionregistration.k8s.io   Local        True                       3d23h
[root@tpaas ~]# kubefedctl enable clusterrole
F1230 00:12:28.599723    5416 enable.go:111] Error: Error listing api resources: …
```
> exec enable cmd ignore ignore some apiservices error

- charts/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
- charts/kubefed/charts/controllermanager/templates/post-install-job.yaml
- charts/kubefed/values.yaml
- scripts/deploy-kubefed.sh
- scripts/pre-commit.sh
- scripts/util.sh
Signed-off-by: Hector Fernandez <hectorj@gmail.com>
The upgrade path from v0.5.0 to v0.6.0 was failing due to the following error:
```
Error: UPGRADE FAILED: cannot patch "kubefed" with kind KubeFedConfig: admission webhook "kubefedconfigs.core.kubefed.io" denied the request: spec.featureGates.name: Unsupported value: "RawResourceStatusCollection":
```
The running admissionWebhook was not upgraded by the time the new kubefedconfig was updated. Therefore we needed to add certain hooks to the created resources. Once I added those, I managed to upgrade from v0.3.0 --> v0.4.0 --> v0.5.0 --> v0.6.0 without any issue.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …
> fix: broken upgrade path from previous versions

- pkg/client/generic/genericclient.go
- pkg/controller/sync/controller.go
- pkg/controller/sync/dispatch/managed.go
- pkg/controller/sync/dispatch/unmanaged.go
- pkg/controller/util/deletionannotation.go
- pkg/controller/util/deletionannotation_test.go
- test/common/crudtester.go
- test/e2e/deleteoptions.go
This PR implements PR #1348 to support DeleteOptions when deleting resources in member clusters.  When deleting a federated resource with `kubefed.io/deleteoptions` annotation, it will be deserialized as a DeleteOptons object and apply to the delete operation.
Fixes #1348
> Feature: support DeleteOptions when deleting resources in member clusters 

- docs/cluster-registration.md
- pkg/kubefedctl/join.go
Kubefedcluster's cadata build from member cluster's serviceaccount, it work well when kubefed directlly conntect to member cluster. In my case, kubefed connect to a proxyserver (it proxy all apiserver's traffic), and the proxyserver has a independent cabundle.
Fixes #
> kubefedcluster use cadata in kubeconfig file

- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/schedulingmanager/controller.go
- pkg/controller/schedulingpreference/controller.go
- pkg/controller/status/controller.go
- pkg/controller/sync/controller.go
- pkg/controller/util/worker.go
Signed-off-by: Bruce Ma <brucema19901024@gmail.com>
This PR will help to enable workqueue metrics for all controllers.
Client-go has implemented [a built-in metrics](https://github.com/kubernetes/client-go/blob/fa8f4cc307b81b125f6beb2cea6f093ed9e3c069/util/workqueue/metrics.go#L72-L90), but it will be disabled when created workqueue is nameless [https://github.com/kubernetes/client-go/blob/fa8f4cc307b81b125f6beb2cea6f093ed9e3c069/util/workqueue/metrics.go#L231](https://github.com/kubernetes/client-go/blob/fa8f4cc307b81b125f6beb2cea6f093ed9e3c069/util/workqueue/metrics.go#L231) .
So this pr is trying to assign a unique name for each controller(workqueue), and this name is usually **the lowercase singular kind** which is being reconciled by this …
> enable workqueue metrics for all controllers

- cmd/controller-manager/main.go
Ref to #1372 , because of importing race as [https://github.com/kubernetes-sigs/kubefed/issues/1372#issuecomment-801732030](https://github.com/kubernetes-sigs/kubefed/issues/1372#issuecomment-801732030), workqueue metrics do not work now.
And this PR try to use an import with highest order to fix this.
Fixes #1372 
Signed-off-by: Bruce Ma <brucema19901024@gmail.com>
> bugfix: register workqueue metrics in controller-runtime firstly

- charts/kubefed/charts/controllermanager/crds/crds.yaml
- go.mod
- pkg/apis/core/v1beta1/kubefedcluster_types.go
- pkg/apis/core/v1beta1/kubefedcluster_types_test.go
- pkg/apis/core/v1beta1/suite_test.go
- pkg/apis/core/v1beta1/validation/validation.go
- pkg/apis/core/v1beta1/validation/validation_test.go
- pkg/controller/util/cluster_util.go
- pkg/kubefedctl/join.go
- pkg/kubefedctl/join_test.go
- pkg/kubefedctl/suite_test.go
There are certain scenarios where a kubefed cluster can be behind a NAT gateway or DMZ. kubefed needs to be able to talk to these specific clusters using a proxy url. In addition, kubernetes supports (k8s > v1.19) the definition of a proxy-url field in the kubeconfig for the clients. This simplifies the communication against these clusters.
Kubefed clusters could require specifying a Proxy URL in addition to a CaBundle, therefore we should consider adding a ProxyURL field to the kubefed cluster object.
Fixes https://github.com/kubernetes-sigs/kubefed/issues/1376
**Special notes for your …
> feat: add a proxy url field to kubefed clusters

- pkg/controller/sync/controller.go
- pkg/controller/sync/status/status.go
- pkg/controller/sync/status/status_test.go
Federated resources that have target resources without status field are constantly evaluated as "changed", if RawStatusCollection is Enabled. This triggers an infinite loop when multiple FederatedResources are created at the same time in the cluster.
Also, this PR applies to collectedStatuses the same transformation that is applied to the FederatedResource status (json.Marshal - json.Unmarshall), so to prevent avoidable changes (and reconciliations) to the FederatedResources.
Fixes #1373
> Infinite reconciliation loop (rawstatuscollection)

- cmd/hyperfed/main.go
we're facing (as described here: #1386 and #1372) a racing condition on workqueue metrics registration, between 
* k8s.io/component-base/metrics/prometheus/workqueue
* sigs.k8s.io/controller-runtime/pkg/metrics
what we want is `sigs.k8s.io/controller-runtime/pkg/metrics` to get registered first, but both of:
- cmd/controller-manager/main.go
- cmd/hyperfed/main.go
have a dependency from `k8s.io/apiserver/pkg/server`, that is bringing `k8s.io/component-base/metrics/prometheus/workqueue` into the picture (and it gets initialized before `sigs.k8s.io/controller-runtime/pkg/metrics`
this PR (#1386) solved the issue for the `controller-manager` executable produced with `make build`, but it doesn't solve it for the single `hyperfed` executable produced with …
> added blank import to ensure correct workqueue metric registration

- pkg/controller/util/worker.go
- pkg/controller/util/worker_test.go
As we know, `workqueue` is using a map [dirty map[interface{}]struct{}](https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/util/workqueue/queue.go#L78) to deduplicate objects and prevent same object(with same namespace and name) to be reconciled by multiple workers at same time.
This means that the objects enqueued must be *comparable*.
But kubefed is just enqueuing objects of type `*DelayingDelivererItem` which will never be equal (pointer values with different addresses), [https://github.com/kubernetes-sigs/kubefed/blob/16b2f5cc4f05c9e9b696970295f353c56d33aa3a/pkg/controller/util/worker.go#L119-L121](https://github.com/kubernetes-sigs/kubefed/blob/16b2f5cc4f05c9e9b696970295f353c56d33aa3a/pkg/controller/util/worker …
> make objects in workqueue "comparable" to avoid multiple reconciliations on one object at same time

- pkg/controller/util/cluster_util.go
- pkg/kubefedctl/join.go
- test/e2e/scale.go
When use kubefedctl join cluster setting `error-on-existing=false` and `secret-name` have specify value, it will case secret exist error.  Join command demo:
```shell
kubefedctl join newdev --cluster-context newdev --host-cluster-context minikube --kubefed-namespace tpaas-federation --secret-name=minikube-newdev --error-on-existing=false -v 2
```
Fixes #
> Fix error on exiting

- charts/kubefed/charts/controllermanager/templates/aggregate_clusterroles.yaml
- charts/kubefed/charts/controllermanager/templates/clusterrole.yaml
- charts/kubefed/charts/controllermanager/templates/roles.yaml
- pkg/client/generic/genericclient.go
- pkg/controller/federatedtypeconfig/controller.go
- pkg/controller/sync/controller.go
`Patch` is more efficient than `Update` to handle racing conditions on high-frequency changes of objects, which is also recommended by kubernetes spec.
Try to avoid some errors, like [https://github.com/kubernetes-sigs/kubefed/blob/4dbd63b07de4b2bcebf3bd2632e0ec08e254f4c3/pkg/controller/sync/controller.go#L283](https://github.com/kubernetes-sigs/kubefed/blob/4dbd63b07de4b2bcebf3bd2632e0ec08e254f4c3/pkg/controller/sync/controller.go#L283)
> use merge-patch on finalizer operations to resolve racing conflicts

- pkg/kubefedctl/enable/util.go
This PR fixes a logging issue when a resource is enabled using the kubefedctl command. The API output is misleading when there are no errors present.
```
W0505 16:55:32.557140   64360 util.go:138] Api resource found with err <nil>, and error could ignore.
```
Fixes #
> fixed false api resource error log in kubefedctl

- pkg/controller/sync/dispatch/unmanaged.go
- pkg/kubefedctl/disable.go
- pkg/kubefedctl/enable/enable.go
- pkg/kubefedctl/join.go
- test/common/typeconfig.go
- test/e2e/crud.go
- test/e2e/validation.go
As issue #1389 , replaced **Update** in remained codes
Fixes #1394 
> feat:Use patch to replace update in generic client for multi cases

- .github/workflows/build.yml
- .github/workflows/push.yml
- Makefile
Fixes issue when running in Github Actions that a TTY is not available so Docker build fails.
**Which issue(s) this PR fixes**
Fixes #
I don't know how to test this out without merging if the review is OK.
> build: Remove need for TTY when running in Github Actions

- charts/kubefed/Chart.yaml
- charts/kubefed/charts/controllermanager/templates/webhook.yaml
- docs/development.md
- docs/environments/kind.md
- pkg/controller/sync/dispatch/retain.go
- pkg/controller/sync/dispatch/retain_test.go
- pkg/kubefedctl/federate/federate.go
- pkg/schedulingtypes/replicascheduler.go
- scripts/create-clusters.sh
- scripts/download-e2e-binaries.sh
- scripts/pre-commit.sh
- test/common/crudtester.go
This PR upgrades to Kubernetes 1.21 for testing, and uses kind 0.11.1.
Some other changes include using `admissionregistration.k8s.io/v1`, available since Kubernetes
v1.16 (`v1beta1` will be removed in v1.22 so best to get this change in now imo).
Updated docs as necessary.
Fixes #
> Kind and Kubernetes upgrade

- scripts/build-release.sh
- scripts/create-gh-release.sh
Switch to `gh` from `hub`.
Fixes #
I've just used these scripts to release v0.8.0 so they are verified to be working :tada:
> build: Use gh instead of hub CLI for release automation

- cmd/controller-manager/app/controller-manager.go
- scripts/pre-commit.sh
make restclient config configurable
Fixes #
> make restclient config configurable

- pkg/controller/sync/controller.go
- pkg/controller/sync/status/status.go
Currently sync controller won't retry propagting a fed resource on any propagation failure, it's not resonable for some recoverable failures such as quota exceed, lack of permissions, etc. For the quota case, after we expand the quota for the failed cluster, we expect KubeFed to automatically succeed in propagating rather than manually edit the fed resource (which is meaninglessly) to trigger a reconciliation.
This PR enable sync controller to retry with back off on recoverable propagation failure.
> fix: retry on recoverable propagation failure

- charts/kubefed/Chart.yaml
This fixes support to deploy on EKS.
> fix: Support Kubernetes pre-release versions in kubefed chart

- scripts/create-gh-release.sh
This was missed as part of the migration to gh for release activities.
> build: Another fix to release script

- .github/workflows/build-and-test.yml
- .github/workflows/test-and-push.yml
- Makefile
Bumps golang version to latest.
Fixes #
> chore: Bump golang from 1.16.5 to 1.16.6

- go.mod
- go.sum
This PR upgrades github.com/evanphx/json-patch to [v4.12.0](https://github.com/evanphx/json-patch/releases/tag/v4.12.0) which includes fix evanphx/json-patch#146 in order to fix a panic when KubeFed controller reconcile a federated object with negative array index in its overrides.
This upgrade also enables full support on negative array indice in overrides.
Fixes #1466
> upgrade github.com/evanphx/json-patch to v4.12.0

- cmd/controller-manager/app/controller-manager.go
I found that the default QPS and Burst values for the rest-client of the kubefed-controller-manager component were configured very low(5 and 10), causing the component to start very slowly:
```
Waited for due to client-side throttling, not priority and fairness
```
So I set it to a suitable value.
Fixes #
> Increase the default QPS and Burst value of the controller manager

- scripts/sync-up-helm-chart.sh
…gFlags
Used standard bash redirection for avoiding the use of deprecated klogs. In this case they were `--log-file` and `--logtostderr`.
**Which issue(s) this PR fixes** 
Fixes #1470 
> Used standard bash redirection for avoiding the use of deprecated klogs

- charts/kubefed/Chart.yaml
- charts/kubefed/charts/controllermanager/Chart.yaml
- charts/kubefed/charts/controllermanager/templates/webhook.yaml
Fixes the issue of the missing `caBundle` configuration property on `MutatingWebhookConfiguration` when `kubefed` is instaleld with `cert-manager` enabled.
Example error:
```
Error from server (InternalError): error when creating "kubefedconfig.yaml": Internal error occurred: failed calling webhook "kubefedconfigs.core.kubefed.io": Post "https://kubefed-admission-webhook.kube-federation-system.svc:443/default-kubefedconfig?timeout=10s": x509: certificate signed by unknown authority
```
Fixes #
> Fix mutatingwebhookconfiguration CA cert when cert-manager is enabled

- pkg/apis/core/common/constants.go
- pkg/apis/core/v1beta1/validation/validation.go
- pkg/controller/kubefedcluster/clusterclient.go
- pkg/controller/kubefedcluster/controller.go
- pkg/controller/sync/status/status.go
Currently when a ready KubeFedCluster's config become malformed (e.g. by deleting its Secret or some other necessary fields), there's no way to change its status to not ready. This can lead to some misbehavior of KubeFed controller and can also confuse maintainers.
This PR introduce a `ConfigMalformed` condition to KubeFedCluster to correctly reflect the unready status of a KubeFedCluster with malformed configuration.
It also mark `ClientRetrievalFailed` as a recoverable error since it's recoverable when some KubeFedCluster's malformed Secret get fixed.
Fixes #1475
> Introduce cluster config malformed condition to KubeFedCluster

- pkg/kubefedctl/join.go
- pkg/kubefedctl/util/util.go
With `LegacyServiceAccountTokenNoAutoGeneration` feature graduating to beta in
k8s v1.24, a token is not automatically generated when a service account is created.
This commit fixes this by requesting a specific service token account secret which
is populated by the token controller. This is backwards compatible with previous
versions of Kubernetes.
> fix: Use specific service account token secret for join

- pkg/kubefedctl/join.go
Although normally very fast, generation of the SA token is async so poll
the SA token until it exists.
> fix: Wait for SA token to be populated

- scripts/download-binaries.sh
- scripts/sync-up-helm-chart.sh
- scripts/util.sh
Previously this was using kubebuilder provided API server and etcd, but these were very out of date (k8s v1.16), leading to potentially out of date resources and difficulties upgrading to later APIs that were not available in v1.16 (e.g. `networking.k8s.io/v1`).
This commit fixes this by using KinD as the cluster to discover resources to
sync to the Helm chart.
> build: Use KinD for syncing helm chart resources

- scripts/update-bindata.sh
This commit ensures that the downloaded version of go-bindata is used
in the build rather than just any go-bindata in the PATH. This led to
some inconsistencies between data generated in local and CI builds.
> build: Ensure correct go-bindata is used

- Makefile
- docs/development.md
- scripts/download-binaries.sh
`controller-runtime` provides a convenient tool to download various versions of k8s. This commit switches to using that to ensure we use a single version for testing in unit tests and in e2e tests, namely v1.21.x right now so to keep the version stable while just changing the installation mechanism.
> build: Use setup-envtest to download later version of envtest

- charts/kubefed/templates/federatedtypeconfig.yaml
- config/enabletypedirectives/ingresses.networking.k8s.io.yaml
- test/common/bindata.go
- test/common/fixtures/ingresses.extensions.yaml
- test/common/fixtures/ingresses.networking.k8s.io.yaml
`extensions/v1beta1` was deprecated in v1.14,
`networking.k8s.io/v1beta1` was deprecated in v1.19 so this commit moves
straight to `networking.k8s.io/v1` which has been available since v1.19.
Considering k8s is now at v1.24.3 this is a sufficient compatibility
window.
> fix: Move ingress from extensions/v1beta1 to networking.k8s.io/v1
